### ISSUE TITLE
 Replaces shortcuts.vdf with new.

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#1]
This is a problem because it removes all the shortcuts by new ones so if you have non steam games that are not on emulator (kind Uplay) it will remove them.

**Comment by juanrodgil** [comment]
Yes, about that it removes my bnetlauncher items in steam.
I add a parser for them in the steam rom manager, so now its no a problem.
Only if "Save List" works for me, it seems to do nothing in my system!

UPDATE: It seems my shortcuts.vdf was corrupted, i remove the old and save again and now its working

**Comment by FrogTheFrog** [comment]
"LastTimePlayed" is being read as a boolean, while clearly it is not. I have created an [issue](https://github.com/tirish/steam-shortcut-editor/issues/7), but until it is fixed I will use my fork for reading `shortcuts.vdf` which will now throw errors properly and provides a temporary `hackish` solution.
