### ISSUE TITLE
SRM is importing all the roms every time I run it, even if they've already been imported

### ISSUE THREAD

**Issue by PhoneboxCorgi** [SteamGridDB/steam-rom-manager#100]
Am I missing something or is this normal?

I get double games I have to go in and erase every time I run SRM. I'm probably just missing a simple setting or something.

**Comment by FrogTheFrog** [comment]
Hey,

disabling this option should prevent duplicates:
![image](https://user-images.githubusercontent.com/22381748/39535169-ed2aa29a-4e3b-11e8-916e-1b6f59b193ba.png)

However, you'll have to remove earlier entries :/

**Comment by PhoneboxCorgi** [comment]
Thank you! That worked.
