### ISSUE TITLE
Keeping favorites and added categories

### ISSUE THREAD

**Issue by saiichihashimoto** [SteamGridDB/steam-rom-manager#103]
Hi! Loving this software, very well done and it is makes my steam link gaming system amazing!

I'd like to be able to set rom games as favorites and keep them there. The moment I run the software again, it clears any of them that were in favorites.

The same happens for any categories I add through the steam interface. I have a category for games I've beaten, but if I run this software, they're all unset.

Am I missing a setting, or is this a feature request?

**Comment by FrogTheFrog** [comment]
Let's see. Is this option enabled?
![image](https://user-images.githubusercontent.com/22381748/40863857-0a9beb92-65fa-11e8-9a37-eb414bec9431.png)

**Comment by saiichihashimoto** [comment]
I do, yes.

**Comment by saiichihashimoto** [comment]
Well, looking at the description in app, it's saying that if I use Retroarch and have multiple games on different consoles with the same name, I should leave the setting *on*. I don't want to do the alternative, modifying the title. Is this necessary to have added categories remain on games?

**Comment by FrogTheFrog** [comment]
@saiichihashimoto Try out the 2.2.16 release.

**Comment by saiichihashimoto** [comment]
Tested, works, love it, best!
