### ISSUE TITLE
DOSBOX Parser

### ISSUE THREAD

**Issue by Xirious** [SteamGridDB/steam-rom-manager#107]
Any plans to add a DOSBOX parser?

**Comment by kencinder** [comment]
Working on presets for it

**Comment by kencinder** [comment]
See https://github.com/FrogTheFrog/steam-rom-manager/pull/108

As soon as it's merged, you can do `Configuration Presets: Force Download` in SRM Settings, to get the latest presets.

**Comment by Xirious** [comment]
Awesome. Thanks for the update!
