### ISSUE TITLE
Splatoon is not in the Fuzzy DataBase 

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#11]
Please add it:http://imgur.com/a/poNNg

**Comment by FrogTheFrog** [comment]
I use [SteamGridDB](http://www.steamgriddb.com/) as list provider. If it is not in there, I can't do anything. Try contacting owner via Reddit.

**Comment by ghost** [comment]
@FrogTheFrog Many Wii U games are not in the database of SteamGridDB it's a shame, thanks for your help

**Comment by FrogTheFrog** [comment]
@PirhanaPlant As I said, contact [dozennn](https://www.reddit.com/user/dozennn) and ask him to add games titles that are missing. My parser will auto update list if number of entries change (every 12 hours).

**Comment by HEspoke** [comment]
@ThePiranhaPlant I have been working on implementing more titles into the database. Splatoon is listed now. I checked on Wii U titles and all of the ones that are currently playable with CeMu should be in the database. If there are any that are not, please post them here and I will sort it out for you.
