### ISSUE TITLE
SRM & NullDC (Dreamcast)

### ISSUE THREAD

**Issue by Moondraker** [SteamGridDB/steam-rom-manager#110]
Hi.
In Steam, if i press "Game Name"->Play, it only opens the emulator. Doesn't run the game.

Config:
![1](https://user-images.githubusercontent.com/41520523/43038628-cbd80f3e-8d14-11e8-91f7-15a9c5f0a8df.PNG)

![2r](https://user-images.githubusercontent.com/41520523/43038672-b72f7f9e-8d15-11e8-8d70-2c62be21036b.PNG)

What am I missing?
Thanks in advance.

**Comment by FrogTheFrog** [comment]
@Moondraker Hi. Could you try this monstrosity for command line arguments:
```
-config nullDC:Emulator.Autostart=1 -config ImageReader:LoadDefaultImage=1 -config ImageReader:DefaultImage="${filePath}"
```

I'm afraid that command line arguments could potentially make path go over ~250 characters. Steam would just delete anything over ~250 and it wouldn't work again, thus uncheck "Append..." (hidden under "Show advanced options"):
![image](https://user-images.githubusercontent.com/22381748/43039134-bdf3d66c-8d2f-11e8-8b7b-43bf4750cce3.png)

**Comment by Moondraker** [comment]
Thanks mate. That did the trick.
Thou, i can't see the connection, but now i can't launch N64 (Project64) roms trough Steam:  "Exception caught File .\N64System\N64class.cpp Line: 558
It also messed up my generic Dual Shock Mapping, but i managed to fixed it... i think.

**Comment by Moondraker** [comment]
Fixed. Input issue!
Had to use N-Rage input plugin V2 2.2 (generic).

**Comment by FrogTheFrog** [comment]
@kencinder Can you update preset?

**Comment by kencinder** [comment]
Update how? This isn't a preset I've added

**Comment by FrogTheFrog** [comment]
Oh. Uhm, add it then :D
