### ISSUE TITLE
[Request] Keep selected images after modifying parser

### ISSUE THREAD

**Issue by juanma-cvega** [SteamGridDB/steam-rom-manager#112]
Is there any way to maintain the selected images from the generated view after variables are changed in the parser? Yesterday I was playing a bit with the shortcut name generated and each time I changed something, the generated list went back to the first image found from the providers. It's kind of a pain to go through the list of images when you can have hundreds of games in the list. My thinking is that these images could be cached and linked to the name of the file the shortcut is for. If the file name changes, well, nothing can be done there, apart from deleting the cached image. 
Another more complex solution could be to link each game file to a unique ID (from an external game DB maybe?) that matches the game and the console found for the file and then link the cached image to this ID. That way, even if the file changes, the logic would first relink the game to this ID (using any kind of fuzzy logic) and then search for any cached image. 
But the first option is also good 😄

**Comment by UNiXMIT** [comment]
I've just experienced this also so It would be good to have if possible. Thanks
