### ISSUE TITLE
Turn off Retro Gaming Cloud for Default SRM settings

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#114]
Could we please have Retro Gaming Cloud be turned off by default. Having SteamGridDB be the only image retrieval server turned on by default would make SRM more user friendly. Thanks!

**Comment by FrogTheFrog** [comment]
@HEspoke Turned of where? In presets?

**Comment by HEspoke** [comment]
In the Settings > General Settings > Image Provider Settings
This would then have it turned off by default when a user creates a Parser.

![image](https://user-images.githubusercontent.com/26511314/43995977-5f7f2e02-9d87-11e8-8923-e4cd6be90843.png)

**Comment by FrogTheFrog** [comment]
It could cause more confusion for new users. How about I remove it from presets?
