### ISSUE TITLE
Icon graphic used for N64 games hangs steam UI

### ISSUE THREAD

**Issue by aaronjwood** [SteamGridDB/steam-rom-manager#115]
I noticed that when you scroll to the N64 section the icons don't show up, and whatever is trying to be displayed for those icons hangs the steam UI until you scroll the section out of view.

**Comment by HEspoke** [comment]
Could you be a bit more specific with the issue your having? When you say that your steam UI hangs, are you talking about Big Picture Mode? and is this only in your N64 Category within BPM? Please clarify your issue with us. Thanks!

**Comment by aaronjwood** [comment]
This doesn't seem to happen with BPM, only the normal view mode. And yes, it's only within the N64 category and only when that category is in view and expanded. If it's collapsed there's no problem. That coupled with the issue of not seeing the icons next to each game led me to think that it's an issue with the icons.

**Comment by aaronjwood** [comment]
I'll post a screenshot later today once I'm back home.

**Comment by HEspoke** [comment]
Ok, no problem. Also, we have people who can help on our discord server if that's easier for you to post to. The discord link is in SRM.

**Comment by aaronjwood** [comment]
![capture](https://user-images.githubusercontent.com/446283/44244133-3f551e80-a187-11e8-9d0e-f145091c44a0.PNG)
![capture2](https://user-images.githubusercontent.com/446283/44244135-42500f00-a187-11e8-8183-448553aa6750.PNG)

Okay so the first screen shot doesn't really show much other than that the scroll bar on the right is at the very top which should be showing my N64 games. The second screen shot is a piece of Process Explorer which shows the CPU spikes in Steam when I leave the scroll bar in this position (technically showing my N64 section but with the UI sorta frozen in place). 

The little icons on the left are what I was referring to earlier. I assumed that SRM populated these since I'm not pulling them in myself.

Maybe the bug is on Steam's side but whatever it is it seems to relate to the N64 icons not being drawn. You'll notice that if I hide the icons for my entire library the issue goes away:

![untitled](https://user-images.githubusercontent.com/446283/44244293-1ed99400-a188-11e8-8e60-f98bc5dafe66.png)

**Comment by FrogTheFrog** [comment]
Steam is pulling icon images itself, unless you specify your icons manually via SRM

**Comment by aaronjwood** [comment]
Thanks, must be on Steam's end then.
