### ISSUE TITLE
Steam ROM Manager CryptoMalware

### ISSUE THREAD

**Issue by zrk4444** [SteamGridDB/steam-rom-manager#116]
My malware programs are detecting the executable as being CryptoMalware.

**Comment by FrogTheFrog** [comment]
Well, virustotal gives me only these false-positives:
https://www.virustotal.com/#/file/18249a6cf8058b2b4f2e9ba8a43bb1e2d7ca75b79f4759e21bb14ec239c8a4f4/detection
https://www.virustotal.com/#/file/ff64d8c3d775099e234ac55b0499f166307ce64f621c0aec2fa8c01740e96d1e/detection
