### ISSUE TITLE
Edit incorrectly parsed game

### ISSUE THREAD

**Issue by Turnspit1337** [SteamGridDB/steam-rom-manager#117]
While starting my first parse of Gamecube games, everything except "Star Wars - The Clone Wars" went right, which was mistaken for either "Lego Star Wars Clone Wars" or some "Clone Wars Heroes" game.

As I see there is no simple way to manually reparse and select specific games before adding them to Steam?

**Comment by FrogTheFrog** [comment]
There is currently no way to override it via UI. However, by editing `%APPDATA%\steam-rom-manager\userData\fuzzyCache.json` file you can change cached `output` manually (do this while SRM is not running).

**Comment by Turnspit1337** [comment]
Thanks for the fast reply! Now that would be an immensely needed feature in the UI! :-D

Will these changes to the .json file stay in place, even if I reparse stuff?

**Comment by FrogTheFrog** [comment]
Yes, until you manually delete it.

**Comment by Turnspit1337** [comment]
That's a workaround I can totally live with - after all the Rom Managers for Kodi have quit their duty and ICE isn't suported anymore, you're the only one left keeping a possibility to neatly manage my roms alive.

Keep it up!
