### ISSUE TITLE
[Request] Sort Preview by Parsers/Systems

### ISSUE THREAD

**Issue by Turnspit1337** [SteamGridDB/steam-rom-manager#118]
It would be absolutely lovely to be able to have categories for the Parser/System in the Preview window and make the whole thing more overseeable. 

At the moment, with a whole ton of games from many different systems, it's a very messy mass of games with no allocation to a specific Console.

**Comment by kencinder** [comment]
Agreed, being able to collapse the preview by parser would be a big help in checking images.
