### ISSUE TITLE
Super Mario 3D Land incorrect image title

### ISSUE THREAD

**Issue by justintime57** [SteamGridDB/steam-rom-manager#120]
When adding Super Mario 3D Land to SRM, the file title is read as a whacky "The Adventures of Super Mario Bros. 3: Toadally Magical Adventure / Misadventures In Babysitting" instead.

**Comment by FrogTheFrog** [comment]
@HEspoke It seems that `Super Mario 3D Land` is not in the DB. You know what to do :)

**Comment by HEspoke** [comment]
@justintime57 That title is now in the Database. Now you just need to add a Steam grid image for Super Mario 3D Land on the SteamgridDB.com website. If you have any more titles that need to be added you can just mention me on the Discord server. Thanks

**Comment by FrogTheFrog** [comment]
@justintime57 In SRM, go to settings page and redownload fuzzy list.
