### ISSUE TITLE
Add Nintendo Gamecube (+ Wii) - Retroarch - Dolphin Parser

### ISSUE THREAD

**Issue by jorenerene** [SteamGridDB/steam-rom-manager#121]

**Comment by FrogTheFrog** [comment]
Could you expand on what this parser should do?

**Comment by kencinder** [comment]
Think they meant "Preset"

Added in https://github.com/FrogTheFrog/steam-rom-manager/pull/122

**Comment by jorenerene** [comment]
Thank you kindly.
