### ISSUE TITLE
FBA /MAME

### ISSUE THREAD

**Issue by Bboy486** [SteamGridDB/steam-rom-manager#123]
I am trying to get CP1,2,3 Games to launch via SRM. I use FB Alpha to play but I cannot get arguments to work. Should be emulator/rom path/rom

It give me an error in steam when I launch. I searched first before posting.

**Comment by FrogTheFrog** [comment]
I need a little more information. What's the error? Also, could you post generated command line?

**Comment by Bboy486** [comment]
Target - "J:\Emulators and ROMS\emulators\fba_029726\fba.exe"  "J:\Emulators and ROMS\ROMS\Consoles Video Games\CPS\FBA\wwfwfest.zip"
Start In - J:\Emulators and ROMS\emulators\fba_0297

Error - J:\Emulators and ROMS\ROMS\Conso is not supported by FB Alpha

**Comment by Bboy486** [comment]
I was able to launch 1 game using this in target - "J:\Emulators and ROMS\emulators\fba_029726\fba.exe" wwfwfest -r 1920x1080x32

however when i went to use command line arguments in SRM ${title} -r 1920x1080x32

I get an error avsp -r is not supported by FB Alpha. although the game i entered into target above works fine

**Comment by kencinder** [comment]
Please use `Copy configuration to clipboard` located at the bottom right in your parser, and paste it in a reply here.
