### ISSUE TITLE
SyntaxError: VDF | Parse: Open parentheses somewhere

### ISSUE THREAD

**Issue by bmarwell** [SteamGridDB/steam-rom-manager#124]
Hi,

I executed srm for the first time.
In one parseer config I had "D:\Steam" and in another "D:\Steam\" (trailing backslash)
I noticed while some parserer were executing. I stopped it, restartet it and got this error:

`SyntaxError: VDF | Parse: Open parentheses somewhere`
Thats all.

I have no idea what to do now. Thanks :)

**Comment by bmarwell** [comment]
I just found the user config dir. No luck in deleting everything and setting up everything again. I also deleted all entries in steam without luck.

--

Edit: Found the backup files. Now everything works again. I can upload them here for debugging, if interested.
BTW, the app should allow to restore the backup. ;-)

**Comment by FrogTheFrog** [comment]
Hmm, my guess would be that `steam/userdata/<id>/760/screenshots.vdf` got corrupted somewhere in Steam's user config for some reason. There should be a backup file made, try restoring it.

**Comment by bmarwell** [comment]
Hi @FrogTheFrog  I restored the shortcuts.vdf -- you were reading while I was editing my comment. ;-)

**Comment by FrogTheFrog** [comment]
@bmhm In the future this tool will be able to do much more :D Once I rewrite it completely :'(
