### ISSUE TITLE
Preserve Launch Options

### ISSUE THREAD

**Issue by dosentmatter** [SteamGridDB/steam-rom-manager#125]
I am using PCSX2 and don't like the controls for one of the games. I am swapping the left and right analog sticks.

I found out you can set the directory path that PCSX2 looks for `.ini` files with the `--cfgpath="...` launch option.

I would like steam-rom-manager to preserve the custom launch options set per game when saving the regenerated app list:
![image](https://user-images.githubusercontent.com/5732253/48961767-31542e00-ef2c-11e8-8c26-d4c6afbd162e.png)

If we can't preserve the options, perhaps having an option to set launch options inside the "Preview" tab would work. I actually prefer this method because all the data is saved within steam-rom-manager.

The only workaround I can think of right now is creating a duplicate parser. But it would require a parser for each game that needs different controls. I would also have to exclude these games from the main parser (maybe with a subdirectory). Maybe variables can help me by naming the cfgpath based on some variable.

**Comment by dosentmatter** [comment]
My current solution:

1. Duplicate current PCSX2 parser. Rename by appending `"Custom Configs"`: `"Sony PlayStation 2 - PCSX2"` -> `"Sony PlayStation 2 - PCSX2 - Custom Configs"`. This will be a parser for PCSX2 games that require custom control mappings.
2. Edit the new parser. Change ROMs directory by appending `"Custom Configs"`: `"C:\Users\John Doe\Games\Sony Playstation 2"` -> `"C:\Users\John Doe\Games\Sony Playstation 2\Custom Configs"l`
3. Add `--cfgpath` to the command line arguments. `"${filePath}" --nogui --fullscreen --cfgpath="C:\Users\John Doe\Documents\PCSX2\inis_1.4.0-${/ /g|${lc|${finalTitle}}|-}"`. This takes the `${finalTitle}` variable, lowercases and replaces spaces with hyphens. You can then create the directory with something like this: "C:\Users\John Doe\Documents\PCSX2\inis_1.4.0-my-game-name".

This new parser should work for all games that need custom configs. If custom configs aren't required, you could just put it in the original PCSX2 directory.

**Comment by kencinder** [comment]
An easier method would be along the lines of what I use to load IPS patches with Retroarch parsers, where if they don't exist they are simply ignored.

If PCSX2 will load the normal configs, or create them if they don't exist, you can do the following in SRM.

Simply add `--cfgpath="path\\to\\cfg\\${title}"` to your single parser's Command Line Arguments

On the note of having SRM preserve launch options, that's got nothing to do with SRM. Once you change that, Steam changes the Shortcut AppID, and it no longer matches with the images.
Adding them to the preview tab could work, but then you're sifting through games to edit the odd one in a case like this, and you're better off using a variable in the parser itself to set this if one exists.
