### ISSUE TITLE
Request] Global Settings for Steam Directory and Retroarch Executable (Possible others?)

### ISSUE THREAD

**Issue by kencinder** [SteamGridDB/steam-rom-manager#127]
As per title, a setting in SRM's main settings page where you can set your Steam Directory and Retroarch Executable.

Would mean not having to fill this out for each parser you create, and could be set in shipped presets.

I see that `${SteamDir}` exists already, and users could have more than one I suppose, maybe `${SteamDirMain}` or something like that for the main setting?

The Retroarch Executable can be prefilled in Retroarch presets with something like `${RetroarchExec}`

**Comment by FrogTheFrog** [comment]
It is kinda possible right now, but not very user accessible. This issue should go away once I update UI.

**Comment by Corgano** [comment]
+1 on this, steam directory is duplicate on every parser, so i look forward to it being pooped in settings.
