### ISSUE TITLE
[Request] Add 4DO Configuration Preset

### ISSUE THREAD

**Issue by JCAMAR0** [SteamGridDB/steam-rom-manager#128]
Just wondering if it would be possible to add the 3DO emulator as a configuration preset.  I have a few games that I wanted to add to Steam through that emulator.

**Comment by kencinder** [comment]
Done, see #129 

Use `Settings > Configuration Presets > Force Download` in Steam Rom Manager, to update the preset list once the above PR has been merged.

**Comment by JCAMAR0** [comment]
Thank you so much!
