### ISSUE TITLE
Parser doesn't scrape images for files with .m3u extension

### ISSUE THREAD

**Issue by treymerkley** [SteamGridDB/steam-rom-manager#130]
I switched to using .m3u files for the parser instead of .cue so I could use my multi-disc games as well. However, for some reason, even though the parser discovers and adds .m3u games with no issues, the image scraping tool isn't working for it, even though it works for the .cue files. Instead, the parser hangs like it normally does when no images are found, saying ```Remaining parsers: n```, where ```n``` is some number.

**Comment by FrogTheFrog** [comment]
I need a little more information than that to replicate the issue. Could you give me a full file path and your parser settings?

**Comment by treymerkley** [comment]
Yeah, of course, and thank you for your quick response.

```
# Parser type
····Selected: Glob
# Configuration title
····Sony PlayStation - Retroarch - Beetle PSX HW
# Steam category
····${PS1}
# Executable
····/usr/bin/retroarch
# Executable modifier
····"${exePath}"
# ROMs directory
····/run/user/1000/gvfs/smb-share:server=192.168.x.x,share=Server/Games/Sony/PSX
# Steam directory
····/home/user/.steam/steam
# "Start In" directory
····
# User accounts
····
····[x]: Skip found accounts with missing data directories
····[x]: Use account credentials
# User's glob
····${title}@(.ccd|.CCD|.chd|.CHD|.m3u|.M3U|.pbp|.PBP|.toc|.TOC)
# User's glob-regex
····null
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enabled
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[x]: Use fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Command line arguments
····-L /home/user/.config/retroarch/cores/mednafen_psx_hw_libretro.so -c /home/user/.config/retroarch/retroarch-psx.cfg "${filePath}"
····[x]: Append arguments to executable
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Image providers
····Selected: SteamGridDB
# Default image
····
# Local images
····
# Local icons
····
····[ ]: Disable current parser
····[ ]: Show advanced options
```

**Comment by FrogTheFrog** [comment]
It seems that [SteamGridDB](http://www.steamgriddb.com/) currently has some problems with handling requests. There's nothing we can really do about this, just wait :/

**Comment by treymerkley** [comment]
Huh, weird. Running it with .m3u removed and adding in .cue loads images, is it just that they're cached or something?

EDIT: Oh hey, look at that: it looks like it's running again. Thanks!

**Comment by FrogTheFrog** [comment]
They should be cached only for the time while the app is running, but it still should show `Remaining parsers: n`. Could you give me that filename you're having trouble with?

**Comment by treymerkley** [comment]
It was all of the PSX titles, so Final Fantasy IX.m3u, Ninja Shadow of Darkness.m3u, etc.

**Comment by treymerkley** [comment]
Hey, do you have any idea how to contribute artwork to the databases?

**Comment by FrogTheFrog** [comment]
Login to [SteamGridDB](http://www.steamgriddb.com/) and upload them 😄
