### ISSUE TITLE
[Potential oversight] Portable version still has non-portable dependencies in configuration

### ISSUE THREAD

**Issue by Corgano** [SteamGridDB/steam-rom-manager#132]
The portable version of SRM has dependencies in userConfigurations.json that make it useless as a portable app. Most notably

- executableLocation
- romDirectory
- startInDirectory (presumed, not tested)

If you have SRM and all your emulators and roms in one folder and then you move that folder or drive to another location these parameters will break. Other fields like localImages are relative and do not break. 
The fix is simple, allow SRM to check the paths of these directories relative to SRM

**Comment by cbartondock** [comment]
How would you feel about a variable ${srmdir} that could go in those fields and get replaced with the path to the portable srm directory? I ask because I am already making those fields work the variable ${/} (resolves as / on unix and \ on windows), and it would be a small matter to do this also.

**Comment by Corgano** [comment]
Having a variable that resolves to the srm root dir would work. You could also check if any of the directory variables start like x:\ and if they do use the door as is, if they don't assume it's a sub folder. You could even just check if srmrootdir\whatevervar exists, if it does use it, if not use whatevervar on its own. There's lots of ways to do it, so whatever works best with your coding style

**Comment by cbartondock** [comment]
I think the variable is nice because it's consistent with other ways of doing things on SRM, ege ${exepath} resolves to the path to the executable.

**Comment by cbartondock** [comment]
@Corgano Please see if this is fixed to your liking in 2.2.25 and if so close the issue.

**Comment by cbartondock** [comment]
Closing for lack of comment, and I believe it has been sufficiently addressed.
