### ISSUE TITLE
Rom Manager no longer loading images

### ISSUE THREAD

**Issue by GOV47** [SteamGridDB/steam-rom-manager#134]
I used the Rom Manager before to load Gamecube games using the Dolphin Emulator and Steam Link.  Everything worked perfectly, images loaded just fine.   Now I have tried to add NES,SNES,N64 with Retroarch and now when I go to preview the games list I get the blank image with the 'x' for everything.  Even the Gamecube games that loaded the images before.    In the log I am getting the "All available image urls retrieved"  and no error messages.  I have tried to google this problem but didn't see any others having this issue. Any help would be greatly appreciated.

**Comment by FrogTheFrog** [comment]
Hey, just to make sure it is SRM's issue, could you download portable version and test it with some sort of configuration?

**Comment by kencinder** [comment]
Steamgriddb was having issues at the time, doZennn fixed the problem.
