### ISSUE TITLE
[Request] Support Uplay games

### ISSUE THREAD

**Issue by denisidoro** [SteamGridDB/steam-rom-manager#138]
Would it be possible to support [Uplay](https://uplay.ubisoft.com/en-GB) games?

In this case, Uplay.exe would be the "emulator" and the actual game would be a "ROM".

[This link](http://webcache.googleusercontent.com/search?q=cache:9wv9D55lWMoJ:www.myconsole.io/right-way-add-uplay-games-steam/+&cd=16&hl=pt-BR&ct=clnk&gl=br) describes how to add Uplay games to Steam.

As of now, I'm using [steamgrid](https://github.com/boppreh/steamgrid) for this purpose but I'm confident steam-rom-manager could cover that as well.

**Comment by kencinder** [comment]
This is not possible directly with SRM, given how UPlay games are stored and launched. SRM can't know the URL or Executable(And there may be more than one EXE in a directory)

It can however be done with any collection of PC games, if you provide a directory of shortcuts or symlinks.

The following is copied from a pinned message from @Chocobubba on our Discord server.

```
Instead, create a "Rom" folder for your PC games and point SRM at it as if it were an actual rom folder.

Install "Linkshell Extension" http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

Find the .exe of your PC game, right click it, and select "Pick Link Source"

Right click inside your PC Game "rom folder", hover over "Drop As..." and select "Symbolic Link"

Repeat for every PC game. This will take a while, but it only ever needs to be once.

Make sure you name every symlink in your "rom folder" to be as accurate to the real title as possible. (This won't break them)

For your PC parser, use the glob ${title}.*

(If you ever get more PC games, make sure you repeat the process later for those games. If you ever move or rename the original game files, the symlinks will break, but otherwise they're forever even if the game is updated.)
```
