### ISSUE TITLE
RetroArch configs between operating systems.

### ISSUE THREAD

**Issue by LexHDev** [SteamGridDB/steam-rom-manager#139]
There are slight variations in where RetroArch stores the library/cores between operating systems, on Windows it's stored as dlls in the same folder. There are presets that help workaround this by just selecting the library based on the file extension with `-L cores${/}core_name.${os:win|dll|${os:mac|dylib|so}} \"${filePath}\"`

While this might work for Windows and Mac, whenever you try this on Ubuntu, for example, you might run into some unforeseeable consequences. Cores by default are installed to `/usr/lib/gnu-linux-x86-64/cores`, IF the user installed the PPA for RetroArch.

On Arch Linux, RetroArch will use either `~/.config/retroarch/cores` or `/usr/lib/libretro` depending on where they install cores from.
 
I believe the best way to remedy this, would be to direct users to their configs inside of RetroArch and have the user change the directories from the exec argument to match their configs.

Another alternative would be to document the presets, showcasing these caveats. Users who are already using Arch should understand (since they have information about it in their wiki), but I'm sure there are other distributions who might have it stored elsewhere. I'm willing to go through and try a couple of different distributions and see if I can get a table of distributions and their libraries locations.

Thankfully, while the library locations are fragmented between distributions, the file extensions should be the same between them.

EDIT: Made at the request of `kencinder` on the Discord server.

**Comment by kencinder** [comment]
Thank you for the info, that's going to make things a little difficult if you've found that different distributions use different locations.

I tried looking to see if some kind of environment variable could be used, but that too is hit or miss depending on how Retroarch was installed.

If `libretro_directory` could be used as a variable to get that from the config, this would be easy.

**Comment by LexHDev** [comment]
In ` ~/.config/retroarch/retroarch.cfg`, it's possible to check the directory that cores are being saved to. This seems to be pretty universal across distros, and I'm thinking it's just where Retroarch saves to on Linux. 
```
# for libretro cores
libretro_directory = "/usr/lib/libretro"
```
Perhaps you could look into this?

**Comment by LexHDev** [comment]
From the libretro docs: https://docs.libretro.com/guides/cli-intro/

> 
>

> ## Using a config file
> By default, RetroArch looks for a config in various places depending on OS:
> 
> - **Linux/OSX**: `$XDG_CONFIG_HOME/retroarch/retroarch.cfg`, then `~/.config/retroarch/retroarch.cfg`, then `~/.retroarch.cfg`, and finally, as a fallback, `/etc/retroarch.cfg`.
> - **Windows**: `retroarch.cfg` in same folder as `retroarch.exe`, then `%APPDATA%\retroarch.cfg`.
> 
> To override this, use `retroarch --config customconfig.cfg`. If you have some special options you want to store in separate config files, you can use `retroarch --config baseconfig.cfg --appendconfig specialconfig.cfg`. Be sure to pass `--menu` as well if you aren't loading content directly from the command-line, or RetroArch will close immediately after launching. See man-page and/or `--help` for detail.
>

**Comment by kencinder** [comment]
I've looked at that, the problem is SRM would have to pull that from the config, expanding a variable for it. It may be something that can be done, but the developer would have to look at it and sort out how, and implement it.

If you could somehow tell Retroarch when launching, to use the core wherever `libretro_directory` points to, that would be much easier.

eg; `-L libretro_directory${/}4do_libretro.${os:win|dll|${os:mac|dylib|so}}`

**Comment by kencinder** [comment]
So I've figured out I can also use the OS variable to achieve this, I'm just stuck on how to handle more than one possible location for cores on Linux.

`-L ${os:win|cores|${os:mac|cores|/lib/x86_64-linux-gnu/libretro}}${/}nestopia_libretro.${os:win|dll|${os:mac|dylib|so}} "${filePath}"`

@FrogTheFrog Is there any way to have more than one path checked for validity here?
The above assumes that cores are located in `/lib/x86_64-linux-gnu/libretro` on Linux, but they could also be located in `/usr/lib/libretro` or `~/.config/retroarch/cores`

**Comment by kencinder** [comment]
Just a note that I haven't forgotten this...

First and foremost, being able to validate where cores are located is not possible, so we're stuck with choosing a suitable default out of the known locations.

I've done a bit more looking into it, and it seems that regardless of distro in use or method of install, Retroarch will ALWAYS look in `~/.config/retroarch` for assets.

As a result I may opt to go with that for presets, but I need to find some time to test and make sure that cores actually get loaded from the `/cores` directory located in there...or if downloaded ones are even placed in there at all.

If that is not the case and cores are downloaded to wherever Retroarch is installed, I am going to go with the most common location for ease of use by most less-savvy users. That to me would be Ubuntu with RA installed via Synaptic.
I would expect users of more niche distros to know what they're doing and change the preset to reflect their setup if different.

**Comment by cbartondock** [comment]
@kencinder did you make a decision here about the default linux location?

**Comment by kencinder** [comment]
I thought you were planning another Retroarch variable for core location, as discussed in Discord, I would rather not assume and decide for others.

**Comment by cbartondock** [comment]
Oh right good call. Is it a directory variable you need or a path variable? And should I only have the variable appear in settings if SRM is running on Linux?

**Comment by kencinder** [comment]
Full path needed on Linux for sure just to the directory with cores, but windows users could theoretically have cores elsewhere if they wanted to.
Might as well just put it with the main setting for the Retroarch executable, call it something like `${racores}` that can just be inserted into the args for presets.

**Comment by cbartondock** [comment]
Okay `${racores}` is in 2.3.6. I'll close this when we add it to the presets.

**Comment by kencinder** [comment]
#195 will finally address this, with the ability to set your retroarch cores directory in main settings, and all retroarch presets will now ship with `${racores}` variable set for Linux.

Windows and Mac will remain defaulted to `/cores` relative to executable, but can be made to use the variable as well if one wishes.

**Comment by cbartondock** [comment]
Great - closing!
