### ISSUE TITLE
Add a per-game retry button 

### ISSUE THREAD

**Issue by mrturret** [SteamGridDB/steam-rom-manager#14]
Having to re-generate the entire list when an image fails to download is really annoying

**Comment by FrogTheFrog** [comment]
@mrturret I plan to do an early v1.3 pre-releases until final v1.3 release. The next early release (should come out this week) will include this:
![example](https://cloud.githubusercontent.com/assets/22381748/26366894/6823c662-3ff5-11e7-8726-b5c627dc4390.gif)
