### ISSUE TITLE
Duplicate titles

### ISSUE THREAD

**Issue by UNiXMIT** [SteamGridDB/steam-rom-manager#140]
Whenever I generate and save the app list to add new roms to Steam, the roms i have already added previously are added again so I have duplicates. I've already tried unchecking 'Append arguments to executable' but it doesn't seem to help. Any ideas why this is happening or where I can check to see what the issue is?
Thanks

**Comment by JizzyRivers** [comment]
I'm having a similar issue.
![index](https://user-images.githubusercontent.com/29721813/57246803-8b493b80-7014-11e9-9eb4-06285b4719b6.png)

**Comment by kencinder** [comment]
Use `Remove all added app entries` in SRM main settings.

Duplicates are created when you alter the executable or arguments, which changes the shortcut and is how Steam assigns an APPID.

**Comment by UNiXMIT** [comment]
Thanks. Will that remove my saves too?

**Comment by kencinder** [comment]
No, why would it touch your saves? All SRM does is create non-Steam shortcuts, nothing more.

**Comment by UNiXMIT** [comment]
Every time I delete shortcuts from SRM in Steam it seems to lose my saves. Must be something else going on. Thanks.

**Comment by aqxa1** [comment]
There's an annoyance with the "Remove all added app entries" option, in that the chosen cover/steam grid image is reverted to the default when re-generating the app list, rather than storing a reference to the previously selected image.

It would also be nice to be able to remove added app entries on a per-parser basis. As it is, if you make a mistake in the parser configuration you have to remove all shortcuts, rather than just the shortcuts associated with the misconfigured parser.

**Comment by blastermaster77** [comment]
Im on linux and the Remove all added app entries in SRM main settings is grayout, and cannot remove them. 
![Screenshot from 2019-07-12 12-01-26](https://user-images.githubusercontent.com/9307070/61142126-06a7ed00-a49d-11e9-9c9f-37d03a0275ad.png)

**Comment by Teapsalm** [comment]
> Im on linux and the Remove all added app entries in SRM main settings is grayout, and cannot remove them.
> ![Screenshot from 2019-07-12 12-01-26](https://user-images.githubusercontent.com/9307070/61142126-06a7ed00-a49d-11e9-9c9f-37d03a0275ad.png)

Have the same issue and still getting duplicates. Tried the setup version and the portable.

**Comment by cbartondock** [comment]
That is strange that is greyed out on linux. That said please create a separate issue fully describing your setup and problem.
