### ISSUE TITLE
Steam Library Beta categories

### ISSUE THREAD

**Issue by WynterFoxx** [SteamGridDB/steam-rom-manager#144]
Presumably because of Steam Beta's transition from "categories" to the new "collections" system, SRM is unable to create Steam categories for parsers.

**Comment by tjhrulz** [comment]
Also can confirm having the same issue. If no one else can I can try to get around to it and see what is if I can fix it but the soonest I can look is a week from now and I have not done any steam shortcut scripting since ICE was still a thing.

**Comment by TyDodson** [comment]
Steam Has Just made this it's default setup outside of Beta.
I wish I had more programming experiance but I cannot make heads nor tails of altering the source.

**Comment by hectik17** [comment]
on my steam libary my catagorys stayed how they were b4 the new libarey look, i have 2 pcs with steam one pc keept the roms within the catagorys but my other steam install droped all the roms in to uncatagorized leaving my rom catagorays empty. manuly moving them is a big task wich i didnt do, re launching SRM and reabuilding the game list didnt move my roms in to the catagorys ether. would be cool to get a update taht is compatable with the new steam libary, maybe a option to have the banners rotated sidways to fit within the new steam libary banners. anyone working on somthing?

**Comment by doZennn** [comment]
Fixed in c264c4c0ae94193be17fb7384023a265cc4a1853
