### ISSUE TITLE
Download Image for ROM of specific dimensions

### ISSUE THREAD

**Issue by TheFigBird** [SteamGridDB/steam-rom-manager#149]
There is currently no way to get SRM to download the grid art from SteamGridDB by specific dimensions, i.e. 460x215.
This would speed up load times if it were possible for large game collections :)

**Comment by cbartondock** [comment]
You mean like exclude 920x430 artwork for example?

**Comment by cbartondock** [comment]
Not sure what this is asking

**Comment by kencinder** [comment]
> Not sure what this is asking

I'd think it's exactly that, I could see wanting to exclude certain sizes, or having a preference setting like 920x430 preferred over 460x215, or for verticals the Steam sizes over GoG sizes. Outright exclusions probably isn't a good idea (without a possibility of a preference too) as you might wind up where certain games, there is only 1 piece of artwork that exists and doesn't fit your setting.

**Comment by cbartondock** [comment]
Added in master, will be present in the next release.
