### ISSUE TITLE
SRM needs to apply grids to recently played images (and needs logo handling)

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#156]
So during the fallout that is the new library, ive been putzing around trying to determine the path forward for the long-term.

while SRM can now handle several of the other image types, its missing 2.  
the recently played images use the same images as grids, but they have to be designated as such.   steamgrid.exe does this and is open source if someone with the proper background wants to borrow the code ;p

Id argue that you could either have another entry for recently played images to parse from separately, or simply have the current grid entry add to both types by default.   Whatever would be easier I suppose (though the latter makes more sense).   I cant imagine anyone wanting a different recently played image than whats designated as a grid anyhow. 

The logos are also unhandled.  Self explanatory.   

Dont hate me :(

**Comment by doZennn** [comment]
One approach to this is symlink one to the other like I'm doing here: https://github.com/steamgriddb/steamgriddb-manager/blob/ed29e29b3bb8996941a12d711bf30ab6299961ef/src/js/Import.jsx#L190-L191

**Comment by klepp0906** [comment]
well, being just a user - thats foreign'ish to me :p

that being said, if that does the same thing (as steamgrid.exe is) regarding recently played images - why isnt it merged?

Gonna go out on a limb and assume this is due to it being a workaround of sorts?  (since you mentioned symlinks) as it appears steamgrid is placing both files there, not making a symlink/copy.

The downside is it takes up twice the space of course, albeit thats the right way I assume. 

If push came to shove I'm pretty sure I can make the modification you linked and get it built,  just hoping it ends up in there proper at some point I guess.

I'm still waiting to find out if the shortcut parsing issue we discussed in discord thats being worked on by that other fella is going to make it in as without that,  the aforementioned is likely irrelevant.

**Comment by doZennn** [comment]
Fixed in #157
