### ISSUE TITLE
SRM clears steam added launch args every parse

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#160]
Just a reminder for @cbartondock about our discussion over implementing a means to apply args to certain titles so they arent overwritten every time the parser is ran.

it results in needing to re add launch options in steam every time you update shortcuts or art with SRM.  If you have several+ titles that need args, whether it be to force fullscreen, skip launchers etc.. it becomes laborious at best.

<3

**Comment by cbartondock** [comment]
I've been thinking about this and I think a better solution is to give SRM more options to set the launch options individually rather than preserve steam's launch arguments (which I am not sure how to do yet). 

It strikes me that SRM is at it's best when it is doing all the work, eg when it replaces steam completely as the shortcut manager.

**Comment by klepp0906** [comment]
apart from any unforseen caveats, im inclined to agree entirely.  another json where you can do a 

```
},
"SectionName": {
                       "Name of Title": "--args -moreargs",
                       "Name of Title": "-args"
}
```

then an entry in SRM tantamount to the "title from custom variable" entry like "launch arguments from custom variable" that uses the same ${SectionName}

oooooooooor, whatever you think is best.  but that keeps things on par to with the other which is always good.

**Comment by cbartondock** [comment]
Yeah this is pretty much exactly what I will do

**Comment by klepp0906** [comment]
nothing but pure gratitude for your work.  Thank you!

**Comment by klepp0906** [comment]
ever start digging into this mr dock?  I'm a bit bias'd of course, but havent seen you about for a minute so figured id give you a gentle nudge/reminder before the good weather comes and takes everyone much more away lol.   (assuming u live in the states)

**Comment by cbartondock** [comment]
Look for it in 2.2.26 ! As well as possibly adding google images as a provider ....

**Comment by cbartondock** [comment]
Added in 2.2.26
