### ISSUE TITLE
SRM is purging shortcuts from disabled parsers when a new parser is ran

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#163]
Dont know if this is now by design, or a recently introduced bug - but it wasnt the case previously and i dont believe its ideal.

While I do know some work was being done on doubles and remnants, Im not so sure the inability to individually run parsers/update particular collections/categories/shortcuts is the best M/O if the former is the case. 

seems if you run a parser, save, disable it, and then run a new parser, save.  Only the most recently ran parser has its shortcuts saved within steam.

this happens if you run the parsers one after the other with steam closed.  or if you open and close steam in between each parser.

the only way im able to retain multiple collections from individual parsers is by enabling them all in tandem and running/saving them simultaneously.

not ideal obviously.

I posted in discord but figured id slap it here as well.  

i resorted to watching the config>grids folder as opposed to opening and closing steam to check.  Upon saving a subsequent parser you can watch everything from the former(s) POOF.

**Comment by JBAndarelli** [comment]
Tested and managed to reproduce it.

There is some even stranger behavior if both parsers point to the same executable : only the second parser's shortcuts will be saved, but twice in two different Steam categories (named after Parser 1 and 2).

**Comment by cbartondock** [comment]
@klepp0906 This should be fixed in the 2.2.25 update. @Metasabaca just the same executable or the same everything? If two parsers are pointing to the same SteamAppID then I have not idea what will happen, probably all hell will break lose.

**Comment by cbartondock** [comment]
@klepp0906 If you can confirm this is fixed please close the issue!

**Comment by klepp0906** [comment]
fixed! thank you very much
