### ISSUE TITLE
[Feature Request] Skipping the parsing of specific titles entirely

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#164]
The ever growing list.  I figured id post this here in case things get lost in the shuffle in discord etc. 

It would be nice if we could omit certain titles from being parsed.   

When re-running a parser to add new titles, or change something therein, you end up with an entire list of whatever directory youve parsed.   If anything belongs in that directory, but you dont want included - your stuck deleting it from steam manually.   Each time you run SRM, you have to do this.

The more titles you are trying to omit, the more awful this can be.   Even if you have only a few titles that you prefer not be included, deleting an SRM added shortcut from steam, does not remove associated assets as if it were removed via SRM itself.

The solution is skipping the item entirely.   I imagine this will take creating another json to manage?

**Comment by cbartondock** [comment]
Pretty sure you can already do this with a glob-regex parser - you just have to rename the file whateveritsnamewas_exclude.iso or whatever and then switch up your glob regex to exclude it.

**Comment by cbartondock** [comment]
Read FrogTheFrog's docs on glob-regex, I think this is within its capabilities!

**Comment by klepp0906** [comment]
yea in my case, if renaming the file is a requirement its a deal breaker.  The same file(s) are pointed to elsewhere and require a specific name for title matching/art matching/scraping etc. 

Just wanted to omit it(them) specifically from being added to steam without ramfications or considerations outside of that.

It would be something I could see having a wide range of uses in a wide range of cases, but I can also understand entirely if you dont see it the same way, or at least dont see it as being worth your time or any priority.

Ill glance at the docs though.   At least i know its doable in some form.   For me, moving the file(s) before parsing is a lesser evil than renaming, however cumbersome.

**Comment by cbartondock** [comment]
Implemented in 2.3.0
