### ISSUE TITLE
SRM purges logo sizing/positioning

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#165]
Back yet again after testing out some of the new assets and improvements with SRM.  Similar to the args issue, but i think will require being handled in a different way.

If you remove all/remove or re-run a parser all jsons which are created in the grids folder after sizing/positioning a logo are purged.

I can understand this on a remove/remove all, but when re-running a parser, probably best if we have a toggle to do this, or not do this.   Or just skip doing it entirely.

The pain at the thought of someone moving hundreds of logos only to add a new game, run SRM, and POOF.  :P

**Comment by cbartondock** [comment]
Fixed in my PR

**Comment by klepp0906** [comment]
youre an animal.  gonna grab it from your fork rq so i can get onto that phase of the master plan.  Thank you good sir <3

now how is the behavior?  leaves it on a re-parse but removes them on a remove or remove-all?  Or just leaves them period?

will go ahead and close this
