### ISSUE TITLE
Some parsers not searching sub-folders

### ISSUE THREAD

**Issue by 8BitCerberus** [SteamGridDB/steam-rom-manager#167]
The Dolphin Wii parser, for example, only searches in sub-folders and doesn't recognize any roms in the root rom folder, while the Dolphin GameCube parser (non-Retroarch version) doesn't and only recognizes games within the root rom folder.

It would be preferable for all parsers to search both the root rom folder, and any sub-folders within. It would also be preferable to have an option to enable or disable sub-folder searching, in case you want to separate out certain "favorite" games into the root and a sub-folder for everything else, and you only want to import the favorites to Steam.

**Comment by cbartondock** [comment]
You're talking about the presets? That may be, and it's sort of a matter of taste, maybe there was a good reason at some point why Wii games were supposed to be isolated in sub folders and gamecube games not, I'm not sure. However, this behavior is extremely easy to change yourself, eg search subfolders with `ROMS/**/${title}.@(iso|wad)` and only do the root with `ROMS/${title}.@(iso|wad)`

**Comment by kencinder** [comment]
I maintain the presets, and I can assure you this is not the case, the Dolphin Wii preset does not ship set to look inside subfolders (No other preset does infact, except Wii U RPX and PS3 ones designed to look for eboot.bin on a per-game basis, and these are necessary or they do not work at all).

The preset has been modified on your end if it's looking in subfolders.

Presets will not ship automatically set to search subfolders, for 2 reasons. 1: There is a performance hit in doing recursive searching of subfolders. (** is recursive, * is only one level deep) 2: Not everyone will want subfolders to be looked in.
You can do as the above comment mentions, and use double asterisks to have it recurse subfolders if you wish.

Line in question in the preset for Dolphin Wii, does not look in subfolders.
https://github.com/doZennn/steam-rom-manager/blob/master/files/configPresets.json#L3657

**Comment by cbartondock** [comment]
In that case I am closing this issue, thanks for the clarification.
