### ISSUE TITLE
Unknown error from SteamGrid + 403 from retrogaming.cloud

### ISSUE THREAD

**Issue by sivan-koren** [SteamGridDB/steam-rom-manager#168]
Neither image provider seems to be working for me. I'm not sure if it's configuration or if they've changed their API and this just needs an update.

I'm using 2.2.23

Thanks for your help!

**Comment by Trozmagon** [comment]
I've got the same issue:
Unknown error received from "SteamGridDB" for "*": {"code":"CERT_HAS_EXPIRED"}

**Comment by stubby326** [comment]
+1

**Comment by ctoncic** [comment]
Same here.

Unknown error received from "SteamGridDB" for "****": {"code":"CERT_HAS_EXPIRED"}
Error received from "retrogaming.cloud" for "****" (403: http://retrogaming.cloud/api/v1/game?name=****).

**Comment by doZennn** [comment]
SteamGridDB is fixed, retrogaming.cloud has been dead for years.
