### ISSUE TITLE
Steam Directory?Ubuntu

### ISSUE THREAD

**Issue by scollar71** [SteamGridDB/steam-rom-manager#169]
Ubuntu 19.10
SRM generate app list fails due to steam user account credentials

> Warning! No user accounts found, it could be due to one of the reasons below:
 - incorrect Steam directory;
 - no user has ever logged in;
 - Steam does not save user credentials ("Show advanced options -> User accounts -> Use account credentials").
If you're seeing this, preview won't be generated for this configuration.> 

Directory I'm using is
/usr/bin/steam

**Comment by FanderWasTaken** [comment]
> Directory I'm using is
> /usr/bin/steam

Yeah, it should be _/home/your_username/.steam/steam/_

**Comment by cbartondock** [comment]
Closing this as answered
