### ISSUE TITLE
All games are not read. What could be missing?

### ISSUE THREAD

**Issue by audie2k3** [SteamGridDB/steam-rom-manager#17]
For example Spider-man iso not get recognized. Do you know why?
![image](https://user-images.githubusercontent.com/6557999/27206723-de8bc17c-51fe-11e7-90b6-e344662f4dbb.png)
![image](https://user-images.githubusercontent.com/6557999/27206821-7bf9ee52-51ff-11e7-98a1-bff6137298ad.png)

**Comment by FrogTheFrog** [comment]
@audie2k3 Your `User's glob` field is wrong. You have set `ROMs directory` to `E:\ROMs\PS2` and your `.iso` file is `E:\ROMs\PS2\open gl games\Ultimate Spider-man.iso`. Parser is then left with  `open gl games\Ultimate Spider-man.iso` to work with. `open gl games` matches `${title}` and `*` matches `Ultimate Spider-man`. You want `${title}` to match `Ultimate Spider-man` and some random directory to match `*`. Therefore, setting `User's glob` to `*/${title}.iso` should do the trick.

**Comment by audie2k3** [comment]
Still a no go... This is not the only game that is having trouble to read. I have an copy of Zone of the Enders  and Zone of the Enders -The 2nd Runner. It would read Zone of the Enders and miss Zone of the Enders -The 2nd Runner.  And I am also having trouble with zip file for snes.

Thank you for your response and development. I hope I can get this iron out.

![image](https://user-images.githubusercontent.com/6557999/27249589-c25f474a-52de-11e7-992b-572dfe6450ac.png)
![image](https://user-images.githubusercontent.com/6557999/27249594-d5009d68-52de-11e7-9b6c-d8a11445a4b8.png)

**Comment by FrogTheFrog** [comment]
@audie2k3 Change `User's glob` to `${title}`. If it works, copy-paste event log here so that I can have something to work with. If it doesn't work, I guess I have a new bug :/

**Comment by audie2k3** [comment]
hmmm... It worked

Resolved Steam categories:
  PlayStation 2
 
[1/1]:               Title - Ultimate Spider-Man.ISO
[1/1]:         Fuzzy title - Ultimate Spider-Man.ISO
[1/1]:           File path - E:\ROMs\PS2\open gl games\Ultimate Spider-Man.ISO
[1/1]:   Complete shortcut - C:\Program Files (x86)\PCSX2 1.4.0 (openGL)\pcsx2.exe "E:\ROMs\PS2\open gl games\Ultimate Spider-Man.ISO" --fullscreen --nogui
[1/1]:       Image queries - Ultimate Spider-Man.ISO
 
"PCSX2 OPen GL" parser test is completed.

**Comment by FrogTheFrog** [comment]
@audie2k3 The problem you have is that parser is case-sensitive. Therefore, `iso` != `ISO`. Set `User's glob` to `*/${title}.ISO`. If you don't have any other files inside `open gl games` (apart from other game files), just set it to `*/${title}.*`. It will retrieve all files with any extension.

**Comment by audie2k3** [comment]
okay, I see. This solved all my other missing game issues as well. Thank you so much!
