### ISSUE TITLE
SRM allows using Unicode characters in tags but will not create the tag

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#170]
Scenario 1:

- You can put something like this: **${CONSOLE PSP}**
- You can save the configuration.
- It will work (tag will be created).

Scenario 2:

- You can put something like this: **${[🎮](https://unicode-table.com/en/1F3AE/) PSP}**
- You can save the configuration.
- It will _not_ work (tag will _not_ be created).

**Comment by cbartondock** [comment]
Does steam allow these?

**Comment by ghost** [comment]
> 
> 
> _Does steam allow these?_

Yes.

**Comment by cbartondock** [comment]
Okay then then that's interesting, I'll look into it.

**Comment by ghost** [comment]
> 
> 
> _Okay then then that's interesting, I'll look into it._

Thanks.

**Comment by cbartondock** [comment]
Tracked the issue to the library we use to do vdf reading and writing. Opened an issue with them [here](https://github.com/node-steam/vdf/issues/2). Hopefully this will be fixed when that issue is fixed.

**Comment by cbartondock** [comment]
Fixed in 2.2.32
