### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by Unknow0059** [SteamGridDB/steam-rom-manager#171]
The link in the "Casual users" section of the readme is broken.
> For casual users
> Visit [Steam ROM Manager's](https://frogthefrog.github.io/steam-rom-manager) github page for more information.

**Comment by FanderWasTaken** [comment]
Ya can still get pre-compiled builds from [releases page](https://github.com/doZennn/steam-rom-manager/releases).

**Comment by Unknow0059** [comment]
Right.
I assumed there would be some useful information in there other than "where to get download".

**Comment by FanderWasTaken** [comment]
Technically all the useful info is in [README.md](https://github.com/doZennn/steam-rom-manager/blob/master/README.md) 😅

**Comment by Unknow0059** [comment]
Then why have this file - meant for casual users - be useless? If it's useless, it should be removed altogether.

**Comment by DanMossa** [comment]
Added it in #173

**Comment by cbartondock** [comment]
Looked up that link in wayback machine, here: https://web.archive.org/web/20181222193444/https://frogthefrog.github.io/steam-rom-manager/

It didn't contain anything except a nice layout and the videos that are still in the docs folder of this repository.

**Comment by cbartondock** [comment]
I am updating the readme for 2.2.25, at which point this issue should be closed.

**Comment by cbartondock** [comment]
Actually, all the layout info is in that docs folder. All we need to do is go to settings and [enable github pages](https://help.github.com/en/enterprise/2.14/user/articles/configuring-a-publishing-source-for-github-pages)

and voila the webpage you mentioned will be back up at https://dozennn.github.io/steam-rom-manager
