### ISSUE TITLE
Images do not save in Steam library on linux with v2.2.23

### ISSUE THREAD

**Issue by FanderWasTaken** [SteamGridDB/steam-rom-manager#172]
Games are being detected, images are loaded in SRM, but as soon as I boot Steam: games are there, but no images. v2.2.21 works fine (I'm using AppImage, since I'm on Fedora). 
[log.txt](https://github.com/doZennn/steam-rom-manager/files/4465218/log.txt)

**Comment by dairefagan** [comment]
Same issue.

**Comment by 42Swampy** [comment]
Me too.

**Comment by cbartondock** [comment]
I don't have a linux machine to test this on unfortunately so I'm not sure what's going wrong

**Comment by PithPossum** [comment]
I can confirm the issue.
2.2.21 works fine
from 2.2.23 to 2.2.25, no images on steam.

I have done a bit of inquiry and it appears the userdata/XXXXXX/config/grid is not populated at all with the latests.

**Comment by cbartondock** [comment]
Fixed in 2.2.26
