### ISSUE TITLE
Ability to escape special characters in glob

### ISSUE THREAD

**Issue by nicholasbrantley** [SteamGridDB/steam-rom-manager#174]
Is it possible to escape special characters in the glob parser? Part of my folder naming is "Game Title [extra info]" and I would like to capture the title without the [extra info] part, but [ and ] are special characters. Glob escaping would use \ but the configuration doesn't allow this character (says its a windows directory character)

**Comment by cbartondock** [comment]
Generally speaking naming directories using regex characters is bad form, but yeah I'll look into some kind of escape system

**Comment by kencinder** [comment]
This is already available under the `Fuzzy Matching` options as `Remove (...) and [...] brackets` and there are examples in the info pane for `Title Modifier` to do it when not using fuzzy matching.

You can't use it in the glob itself, as the glob is what picks up/detects your files. If you used it in the glob, you wouldn't get any matches that *have* those brackets, as you're telling SRM to ignore them if you did.

Use fuzzy matching option, or title modifier to achieve this. Glob != Final Title

**Comment by cbartondock** [comment]
@Nickno95 please validate that the above works and I will close the issue.

**Comment by cbartondock** [comment]
Closing for lack of comment
