### ISSUE TITLE
Error launching game when in big picture mode

### ISSUE THREAD

**Issue by lamvuong2019** [SteamGridDB/steam-rom-manager#175]
I have tested to launch a PCSX2 game in normal mode it launches, however when I tried to launch it in big picture mode, streaming to the tv via an nvidia shield tv. It failed with unexpected parameter.

**Comment by lamvuong2019** [comment]
I can confirm if it is in big picture mode standalone, not connected with the shield tv the game is able to be launched.

**Comment by cbartondock** [comment]
This has absolutely nothing to do with SRM. Does it work when the shortcut is added by hand? I bet not

**Comment by lamvuong2019** [comment]
> 
> 
> This has absolutely nothing to do with SRM. Does it work when the shortcut is added by hand? I bet not

I don't know what the issue is but when I use the geforce experience / geforce now this happens. If I use steam link it is working fine.

There is a workaround, you just need to replace the spaces in the file name to _ and it loads.

**Comment by cbartondock** [comment]
Could you close the issue? I don't think this is SRM's doing at all.
