### ISSUE TITLE
Not saving app list

### ISSUE THREAD

**Issue by STi81** [SteamGridDB/steam-rom-manager#182]
v.2.2.31
Parsers is "green". Preview found all my games and artwork for it, but app list is not saving. Stuck on "Saving added category information to localconfig.vdf"
log
Updating user configurations with new fields
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Populating VDF list.
Creating backups.
Reading VDF files.
Merging VDF entries.
Saving added category information to localconfig.vdf

**Comment by cbartondock** [comment]
Fixed in 2.2.32. Please follow the instructions for the release and confirm.
