### ISSUE TITLE
Everytime I open SRM I get it won't load community presets. Here is my log. How can I fix this.

### ISSUE THREAD

**Issue by Smartguy9861** [SteamGridDB/steam-rom-manager#184]
Saved configuration presets are invalid!
Permanent file saving is disabled until this issue is resolved.
Try to manually fix errors yourself (file - C:\Users\Smart Guy\AppData\Roaming\steam-rom-manager\userData\configPresets.json)
or seek help on github or our official discord channel: 
[
	{
		"keyword": "required",
		"dataPath": "['~Generic~'].parserInputs",
		"schemaPath": "#/patternProperties/%5E.%2B%24/properties/parserInputs/required",
		"params": {
			"missingProperty": ".steam"
		},
		"message": "should have required property '.steam'"
	}
]

**Comment by cbartondock** [comment]
Forcibly download config presets in settings

**Comment by matehuos** [comment]
> Forcibly download config presets in settings

I got the same error. I tried to force the download but didnt work either. I'm using v2.2.34
