### ISSUE TITLE
error: Steam has changed their internal database structure, this parser needs to be fixed

### ISSUE THREAD

**Issue by eco9898** [SteamGridDB/steam-rom-manager#185]
I downloaded this today to use apps with steam and I set it up based off the steam config defaults but I keep getting this error
Testing "Steam" parser (SRM version - 2.2.31 Non-Portable).
Operating system is "Windows 10"
Testing failed
Steam parser failed with fatal error: Steam has changed their internal database structure, this parser needs to be fixed

**Comment by cbartondock** [comment]
Thanks ! I will look into it.

**Comment by cbartondock** [comment]
Which version of steam are you running? Beta client or normal? Also make sure it is up to date.

**Comment by eco9898** [comment]
At the time it was the latest non beta release, however there was a steam update today that I have now downloaded. The same error still occurs

**Comment by cbartondock** [comment]
Could you send me your `C:\Program Files (x86)\Steam\appcache\appinfo.vdf` either here or on discord?

**Comment by eco9898** [comment]
[appinfo.zip](https://github.com/doZennn/steam-rom-manager/files/4720826/appinfo.zip)
I have zipped it and uploaded it .... I hope

**Comment by eco9898** [comment]
[sharedconfig.zip](https://github.com/doZennn/steam-rom-manager/files/4728165/sharedconfig.zip)

**Comment by cbartondock** [comment]
Hmm everything seems to be good.. I am going to upload a new version with more careful error logging in that parser. If you could try again with that version (it will be 2.2.34), we can hopefully figure it out. Also, can you make sure you have read permissions for your steam directory? Don't know why you wouldn't but still.

**Comment by cbartondock** [comment]
Please update to 2.2.34. It has better logging for this parser. You will most likely still get the error, but it will include more information which should help me fix it for the next build. Thank you

**Comment by eco9898** [comment]
All available image urls retrieved.
Executing parsers.
Fatal error occurred. See event log for details.
Steam parser failed with fatal error:
 Steam has changed their internal database structure, this parser needs to be fixed. Full error:
 TypeError: Cannot convert undefined or null to object

**Comment by cbartondock** [comment]
Great thanks for posting it, I will drill down and try to figure out what is null. That said the fact that something is null probably means something is not being read in properly (one of the two files I asked you for). I will look into it.

**Comment by cbartondock** [comment]
Have you had multiple people log into steam on this computer? If so I would recommend restricting which user account srm looks at in the "User Accounts" field. Just use ${your_username}

**Comment by eco9898** [comment]
Cool, this is what fixed the problem, thank you
