### ISSUE TITLE
Entries not being added/updated, no errors visible

### ISSUE THREAD

**Issue by SaltyBet** [SteamGridDB/steam-rom-manager#186]
This is all that appears on the log:

All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Populating VDF list.
Creating backups.
Reading VDF files.
Merging VDF entries.
Saving added category information to localconfig.vdf

**Comment by cbartondock** [comment]
Did you follow the instructions upgrading to 2.2.32? Could you press CTRL+SHIFT+I with SRM open to open the debugger, go to the console tab of the debugger, try running it again, and paste exactly the error it gives you in the debugger?

**Comment by SaltyBet** [comment]
> Did you follow the instructions upgrading to 2.2.32?

Yes.

> Could you press CTRL+SHIFT+I with SRM open to open the debugger, go to the console tab of the debugger, try running it again, and paste exactly the error it gives you in the debugger?

Attached: [error.log](https://github.com/doZennn/steam-rom-manager/files/4714225/error.log)

**Comment by cbartondock** [comment]
Oh wow that's exactly the same error I was pretty sure I had fixed in 2.2.32. Are you using portable or installed? And when you look at the log it says 2.2.32? Edit: and which OS and Steam Client branch (beta or regular)?

**Comment by SaltyBet** [comment]
> Are you using portable or installed?

Portable.

> And when you look at the log it says 2.2.32?

It says **2.2.32** in **About** page.

> Edit: and which OS and Steam Client branch (beta or regular)?

Windows 10. Regular branch.

**Comment by cbartondock** [comment]
Can you zip your leveldb directory and send it to me here or on discord?

**Comment by cbartondock** [comment]
Fixed in 2.2.33
