### ISSUE TITLE
[Enhancement] Custom icons

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#19]
Examples:
![2017-06-22_16-45-58](https://user-images.githubusercontent.com/26660840/27441821-ead2c578-576e-11e7-948f-3316731abcce.png)
![2017-06-22_16-45-58e](https://user-images.githubusercontent.com/26660840/27441822-eadbabd4-576e-11e7-9a7d-e82a271a7c0c.png)

**Comment by HEspoke** [comment]
First of all, I love the original post pictures. Its basically the games that I have been playing recently haha. Could @ThePiranhaPlant explain a little bit to me what the request is? It looks like  you already have SRM looking for Local Images for your roms, so what would be the need for "custom icons"? 
Thanks

Edit: Now that I have been using the program for a little bit I think I know what @ThePiranhaPlant needs. I will address it in my next post on this thread

**Comment by HEspoke** [comment]
I have a large amount of Steam Grid images that I pulled from a program called Streamgrid . I used that program to fill in the gaps for my Big Picture Mode images when ICE found all that it could from consolegrid (RIP). Could @FrogTheFrog please consider the following feature that would help with the custom icon problem that @ThePiranhaPlant mentioned and help the program A LOT in the future. 
What we need is a option on the left on the program named "Global Settings" (or something like that). The global setting section would help with configuring settings across all emulator. One of the settings would be Local Images. This local images setting would pull from a user defined folder and fill in the "Preview" option with your own local images when you are going to parse all of your emulators. It would integrate your local images when you are "generating your app" list. This way you can set your local images folder one time for all of your steam grid images for all games instead of doing it on a single emulator basis. Once @FrogTheFrog integrates this "Global Settings" option (if its possible) on the left side of the GUI he can add more options withing that setting in future updates.

**Comment by HEspoke** [comment]
Addition: Having all of the Steamgrid image sources listed with toggle switches next to them. This way the user can turn off or on these sources before going through the Parsing process and creating the "App List". This would be especially useful for users that have a large library of ROMs.
Example:
X Retrogaming.cloud
X Consolegrid.com
X Steamgriddb.com
X Local Images

**Comment by UndarkAido** [comment]
https://github.com/Hafas/nostegama has this feature, and I'd really love to see it here.

**Comment by FrogTheFrog** [comment]
@ThePiranhaPlant, @HEspoke, @Aidoboy What should be displayed when SRM can't show the icon itself (unsupported format for SRM, but not for Steam... maybe)? Also should the icon's size remain fixed or should it scale with the grid image? Finally, what should be the max/fixed size for icon?

**Comment by UndarkAido** [comment]
Default icon should be the exe icon. 

From [this article](https://www.howtogeek.com/179370/how-to-add-non-steam-games-to-steam-and-apply-custom-icons/)
"Icons: These are standard icons, you’ll need either a .exe with an embedded icon (like the .exe of the app itself, if it has an icon you want) or the icon you want to use as a .PNG  or .TGA file that’s square (e.g. 256 x 256 pixels) like a regular icon file." (Or it should be an ICO file)

**Comment by FrogTheFrog** [comment]
That's not what I meant. Anyway, it does not matter now. This is how it will look like when the icon is found and I can display, and when it's found, but I can't display it:

![image](https://user-images.githubusercontent.com/22381748/29243378-5448fdce-7fa6-11e7-9c0b-84be0410d2a6.png)

or

![image](https://user-images.githubusercontent.com/22381748/29243396-bdd9a626-7fa6-11e7-9111-6da46a711ea0.png)

Which one is better? I should also mention, that SRM won't be able to display icons that are embedded in `.exe`. To achieve that, I would need to use Windows API, .Net or just write my own code to parse `.exe` in binary format. First two "solutions" would not allow SRM to be run on linux and the third one is a pain in the ass to write from scratch. If someone would write it, I would gladly implement it.

**Comment by FrogTheFrog** [comment]
Needless to say, you will be able to select from multiple icons if you wish. For example, first one would be the real one and another one could be a fallback if the first one does not exist.

**Comment by HEspoke** [comment]
@FrogTheFrog The second image is the one I would go with. This one = https://user-images.githubusercontent.com/22381748/29243396-bdd9a626-7fa6-11e7-9111-6da46a711ea0.png

I am not quite sure what @Aidoboy is talking about. As it currently stands, the Stand View of Steam already previews the EXE file embedded image by default. For my emulators, the EXE is shown for all my emulators and that already happens in Steam vanilla.

One question for you @FrogTheFrog , if SRM cant find the EXE image and it shows the eye with the line through it, will SRM populate that eye image in all the EXE images for Steam Standard View?

**Comment by FrogTheFrog** [comment]
@HEspoke SRM can't display EXE image, however it does not mean that Steam can't. The eye will be shown only in SRM. I don't really care what you choose as an image, I'll just pass IT along into Steam configuration and then Steam will have to deal with it.

**Comment by HEspoke** [comment]
Cool, that's exactly how I would want SRM to function. Thanks 

-Tyler

**Comment by UndarkAido** [comment]
@FrogTheFrog Would this work? https://www.npmjs.com/package/icon-extractor

**Comment by UndarkAido** [comment]
@FrogTheFrog Can't you just not load it on mac/linux?

**Comment by FrogTheFrog** [comment]
@Aidoboy Hmm... I will try something.

**Comment by FrogTheFrog** [comment]
@Aidoboy It seems that .NET can now be compiled for linux too, however icon extractor uses Windows specific code, which will not work on linux. As for the question whether I could just load it on Windows - yes, I believe I could. However, I really don't want to separate code into "Windows and others"...

**Comment by UndarkAido** [comment]
It would just be that one bit of code, and it's for a Windows-only feature
that's worthless on other systems but is really nice to have on Windows.

**Comment by FrogTheFrog** [comment]
@Aidoboy So far it's pain in the ass. NET code seems to compile, but there are problems with paths and the fact that icon extractor uses one event emitter without ability to pass a function callback to it. I will keep it as a very low priority and will eventually try to adapt it to this app. For now I'm closing this issue.
