### ISSUE TITLE
Steam parser fatal error

### ISSUE THREAD

**Issue by thedaryen** [SteamGridDB/steam-rom-manager#194]
When using the Steam Parser on latest version (2.3.3):

Fatal error occurred. See event log for details.
TypeError: this.getVariable(...).trim is not a function

Just using the default configuration preset. Had to change the "User Account" attributes to "${andreycout}" in order for it to escape another fatal error as reported in #185 , but this new fatal error occurred instead

**Comment by cbartondock** [comment]
Thanks for reporting. Are you on the normal steam client or the beta client? Also please post your OS and whether you are running the portable version.

**Comment by cbartondock** [comment]
I don't think the new error is a steam parser error. Are you using any variables in the parser? Can you post a link to a pastebin of the output of copying your parser?

**Comment by thedaryen** [comment]
https://pastebin.com/K6xY9412
I'm on steam beta client

**Comment by cbartondock** [comment]
That looks right. Could you try pressing Ctrl+Shift+I and re-running and seeing if any error comes up on the console (assuming you are on windows). Also not that it should make a difference but upgrade to 2.3.4

**Comment by thedaryen** [comment]
I get a warning with the inspector, but it's there as soon as I open SRM, don't need to try to run anything in order for it to be there:

(electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.
log @ electron/js2c/renderer_init.js:227
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/andre/AppData/Local/Programs/steam-rom-manager/resources/app.asar/dist/renderer/Reflect.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/andre/AppData/Local/Programs/steam-rom-manager/resources/app.asar/dist/renderer/common.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///performance-now.js.map:

**Comment by cbartondock** [comment]
Yeah those warnings are normal. Hmmm. I can't seem to reproduce the error on my end. It's just your steam parser?

**Comment by cbartondock** [comment]
Basically one of your variables is returning null (probably title or title modifier) is returning null for a particular game. Not sure why that would be, but I should add better error handling. I will look into it.

**Comment by cbartondock** [comment]
Try changing your title modifier

**Comment by cbartondock** [comment]
Either leave it blank or set it to ${title}

**Comment by thedaryen** [comment]
can't leave it blank, SRM doesn't allow it. ${title} gives me the same error. Typing anything as title modifier gives me the same error.

Tried changing my username setting to something random but it just tells me there's no content in the specified directory when I do so.

I guess there's something unique about my steam game list when compared to yours that's triggering that error. Disabling the steam parser fixes the error, other parsers work correctly.

**Comment by cbartondock** [comment]
Okay thanks for all the info. That's also what I would conclude. One more Q - what does test parser output for the steam parser? Also, here is a portable build which will send me more in depth logging info in the place I think something is wrong. Please give it a go: https://www.dropbox.com/s/menvgabqt2tw5ua/Steam%20ROM%20Manager-portable-2.3.4.exe?dl=0

**Comment by thedaryen** [comment]
Tested the portable one. Same thing.
Test log:
"Testing "Steam" parser (SRM version - 2.3.4 Portable).
Operating system is "Windows 10"
Testing failed
TypeError: this.getVariable(...).trim is not a function"

**Comment by cbartondock** [comment]
The build I sent you had additional error reporting and has allowed me to narrow down the source of the error. Could you please send me your `C:\Program Files (x86)\Steam\appcache\appinfo.vdf` and `C:\Program Files (x86)\Steam\userdata\STEAMID\7\remote\sharedconfig.vdf`? Note that since you already mentioned you have multiple data directories in userdata you will have to figure out which STEAMID is actually yours. I believe for some reason the structure of your steam games database is different from what I am used to - either that or the specification of user account is not sufficiently stopping the parser from trying to parse the data from other (older) account directories. You could test this latter theory by moving out all the folders in `C:\Program Files (x86)\Steam\userdata\` other than the one that belongs to your actual steam account, and then retrying.

**Comment by cbartondock** [comment]
Don't upload those files here by the way, as they may contain sensitive information. You can DM them to me on discord (I am lontanadascienza in the SRM discord)

**Comment by cbartondock** [comment]
Fixed in 2.3.7
