### ISSUE TITLE
Images won't download

### ISSUE THREAD

**Issue by cruderustle** [SteamGridDB/steam-rom-manager#198]
In the Steam ROM Manager, images won't download for games anymore. It constantly says remaining providers: 136 in the upper left and the "Stop image providers" is always at the bottom, making me think that maybe it can't grab the images for some reason? The SteamGridDB website works fine for me.

![Annotation 2020-08-01 104442](https://user-images.githubusercontent.com/27592452/89105122-11089200-d3e4-11ea-8933-91cceaec445d.png)

The games with images are the ones they were set with before this issue arose, and you can only choose from that one image they previously had.

**Comment by jadamsit** [comment]
Also having this issue.

**Comment by Tk144** [comment]
I am having this issue too!

**Comment by Tuxsupa** [comment]
Same here

**Comment by doZennn** [comment]
Fixed, no need to update SRM.

**Comment by benwbooth** [comment]
I'm also having this issue. I'm using Emudeck on the steam deck. It keeps getting stuck on "Remaining providers".
