### ISSUE TITLE
Steam directory specified has no accounts

### ISSUE THREAD

**Issue by killerkomodoohno** [SteamGridDB/steam-rom-manager#199]
```
# Parser type
····Selected: Glob
# Configuration title
····Gamecube
# Steam category
····${Gamecube}
# Executable
····C:\Users\komod\Desktop\Dolphin\Dolphin-x64\Dolphin.exe
····[x]: Follow .lnk to destination (Windows only)
····[x]: Append arguments to executable
# Command line arguments
····--exec="${filePath}" --batch --confirm=false
# Executable modifier
····"${exePath}"
# ROMs directory
····C:\Program Files (x86)\ROMs
# Steam directory
····C:\Program Files (x86)\Steam
# "Start In" directory
····
# User accounts
····${komodolover_oskomodo}
····[x]: Skip found accounts with missing data directories
····[ ]: Use account credentials
# User's glob
····${title}.@(iso|img)
# User's glob-regex
····null
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enable Title from Custom Variable
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[x]: Use fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Image providers
····Selected: SteamGridDB
# Default image
····
# Default tall image
····
# Default hero image
····
# Default logo image
····
# Local images
····
# Local tall images
····
# Local hero images
····
# Local logo images
····
# Local icons
····
····[ ]: Disable current parser
····[ ]: Show advanced options
```
--------
Testing "Gamecube" parser (SRM version - 2.3.10 Non-Portable).
Operating system is "Windows 10"
 
Parser ID: 159788125221496869

Found 1 available user account(s):
  komodolover_oskomodo (steamID64: 76561198352024036, accountID: 391758308)
 
Number of Titles: 0
 
Parser test is completed.
All available image urls retrieved.
Executing parsers.
Fatal error occurred. See event log for details.
Steam directory specified has no accounts
--------

I have logged out of Steam multiple times, used the account ID instead of the username login, and have reinstalled Steam. New to SRM so I'm not sure what the issue is.

**Comment by cbartondock** [comment]
Are your versions of steam and SRM fully up to date? Is there a folder in C:\Program Files (x86)\Steam\userdata called 391758308?

**Comment by killerkomodoohno** [comment]
I have installed version 2.3.11 of Steam Rom Manager and I am in the beta
version of Steam, so it is constantly updating. Yes, there is a folder
there with the exact numbers.

**Comment by cbartondock** [comment]
Can you try filling out the "specify user account field"? I have a feeling you have old directories from people who logged in on your machine prior to a change in the structure of steam's files. Happens often.

**Comment by killerkomodoohno** [comment]
Are you talking about this?

[image: image.png]

I have used my username login, the profile ID, and every combination of the
two settings below this option but I still get the "Steam directory
specified has no accounts" error.

**Comment by killerkomodoohno** [comment]
I have updated to 2.3.11 but the issue still persists.

**Comment by kencinder** [comment]
> I have installed version 2.3.11 of Steam Rom Manager and I am in the **beta version of Steam**, so it is constantly updating. Yes, there is a folder there with the exact numbers.

Beta versions of Steam are likely to have changes that break things, including things that affect SRM. Working fine here on the latest build.

**Comment by killerkomodoohno** [comment]
Got it working a few weeks ago from the subreddit, thanks for reaching out
tho!
