### ISSUE TITLE
Program Hangs

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#20]
I followed all the steps and downloaded the needed dependencies. After I run this command "E:\emulation\SRM\node_modules\electron\dist\electron.exe E:\emulation\SRM\dist\main.bundle.js" The program launches and it says "Loading App" with a great circle and then it says "Loading Settings" with a green circle, then all I get it the dark gray screen that is on the photo below. Please help with this issue, if its user error then please be patient with my understanding of how your program works. Thanks for your time!

![image](https://user-images.githubusercontent.com/26511314/27505398-d789b400-586c-11e7-97ae-8cc7d57609a2.png)

**Comment by FrogTheFrog** [comment]
Can confirm this issue. It might be related to some dependency as it does not seem to occur on project with older dependencies. Might also be an issue with Node.js 8.x.x as I used 7.5.x before.

**Comment by HEspoke** [comment]
Thank you for taking a look at this for me. I am a long time ICE user and I am eager to try out your program and give you feedback.

**Comment by FrogTheFrog** [comment]
@HEspoke After hours of digging, I found out that `rxjs@5.4.1` is responsible. Latest Node.js did not cause any problems (apart from `legacy` debugging, which was replaced by `inspector`). Please confirm that latest push works for you whenever you can and close this issue if it does.

**Edit:**

It was actually a bug :/. Before `rxjs@5.4.1` it was not throw properly. The bug prevented me from disposing `Observable` from inside, however after throwing error, it (`Observable`) disposed itself automatically anyway.

**Comment by HEspoke** [comment]
I tried running it again after loading in your new build. The problem still persist.

**Comment by FrogTheFrog** [comment]
You did rebuild it, right? (Also, your fork is 2 commits behind)

**Comment by HEspoke** [comment]
Looks like the problem is fixed. I had to delete all of the original program data in the folder that your program was stored in. Then I downloaded the new build and started from scratch with rebuilding the program. Now it works, and I will be testing the program out. Thank you for fixing the bug and for your assistance!
