### ISSUE TITLE
Async not working on CEMU games launched through steam

### ISSUE THREAD

**Issue by PoorAndNeedy** [SteamGridDB/steam-rom-manager#200]
It seems the CEMU emulator's ASYNC setting for Vulkan isn't working when launched from steam. Two people describing the issue on Reddit [HERE ](https://www.reddit.com/r/cemu/comments/he5e1x/vulkan_with_async_and_steam/)and [HERE](https://www.reddit.com/r/SteamRomManager/comments/id1inz/is_anyone_else_having_an_issue_where_cemu_vulkan/). I tried messing around with launch settings, but I can't find a workaround.

**Comment by cbartondock** [comment]
I don't think this is an issue with steam rom manager. If the same issue occurs when you add the game manually there is probably nothing SRM can do. If you find a fix that involves a change to our CEMU preset let me know, but more likely the fix will come from CEMU itself.
