### ISSUE TITLE
Changing Game Title in Steam different to Rom Name

### ISSUE THREAD

**Issue by Downtime1989** [SteamGridDB/steam-rom-manager#201]
Hey probably something really simple but looking for a way to change the name of the game that shows up on steam different to what the rom is actually called. got came titles with region codes, disc numbers and games with all caps... driving me mad...

thanks for any help in advance

Downtime

**Comment by cbartondock** [comment]
Are you using fuzzy matching or just file names? eg is your "Title modifier" field set to ${title} or ${fuzzyTitle}? If the former, try changing to the latter or just changing the file name to be what you want it to be. If the latter and it is working for some games but not others, try our built in Exception Manager to overwrite the title for the cases where fuzzy fails.
