### ISSUE TITLE
Flag/Setting for searching more than one directory level deep

### ISSUE THREAD

**Issue by addrum** [SteamGridDB/steam-rom-manager#209]
I'm trying to set up a parser for cxbx reloaded, however specifying the rom directory is causing issues as the cxbx, the "roms" are extracted isos which give you a `.xbe` file and usually a folder full of other game files. You can't load the iso directly and having all the xbe's plus other loose files/folders needed per game in one "rom" directory could very quickly cause conflicts and is generally pretty messy. Is there something existing to help with this or would it be a new feature? Happy to contribute if needed.

**Comment by kencinder** [comment]
You can use something like `*/${title}.xbe` to search one level deep or `**/${title}.xbe` to recursively search. There *is* a performance penalty in doing either, with recursive having a greater penalty...penalty as in parsers will take longer to execute.

**Comment by addrum** [comment]
Fabulous that's done the trick thank you!
