### ISSUE TITLE
Add some kind of warning for Cemu parser

### ISSUE THREAD

**Issue by FanderWasTaken** [SteamGridDB/steam-rom-manager#215]
When adding Cemu games in Steam and using Async shader compilation with Vulkan, you end up with stuff missing and not rendering at all. The issue is caused by Steam, since if you run Cemu as standalone app, it works properly. The fix is to disable Steam's Shader Pre-Cashing: [reddit post](https://www.reddit.com/r/cemu/comments/ji1by2/rendering_issues_when_launching_cemu_via_steam/gani3on/?utm_source=share&utm_medium=web2x&context=3).
I was thinking if it's possible to add some kind of warning to tell people using Cemu parser to disable Shader Pre-Cashing in Steam to fix this issue.

**Comment by kencinder** [comment]
There isn't really a "notes" section in the presets to put something like this, and this issue could be resolved in the future, meaning we'd have to keep track of it and remember to remove it from the preset.

Not really something that belongs in the presets

**Comment by FanderWasTaken** [comment]
> There isn't really a "notes" section in the presets to put something like this, and this issue could be resolved in the future, meaning we'd have to keep track of it and remember to remove it from the preset.
> 
> Not really something that belongs in the presets

Fair enough. I was just trying to fix that issues for days and randomly found that reddit post. Just thought it could be helpful to others, idunno 😓

**Comment by cbartondock** [comment]
There maybe should be a place for comments like this, but for now someone searching will either find this issue or the original reddit post eventually (hopefully). Thanks!
