### ISSUE TITLE
Mixing no/trailing slash in steam directory corrupts `addedItemsV2.json`

### ISSUE THREAD

**Issue by SolitudeSF** [SteamGridDB/steam-rom-manager#219]
If one parser has trailing slash in steam directory and other doesn't, when saving app list, invalid json gets written to `addedItemsV2.json`.

**Comment by cbartondock** [comment]
Very interesting. Looks like we need to do a better job normalizing our inputs. Thanks for pointing this out. As an aside, why not use the global steam directory variable instead?

**Comment by SolitudeSF** [comment]
because i missed the global options completely

**Comment by cbartondock** [comment]
Ah maybe we should do a better job pointing it out

**Comment by kencinder** [comment]
Is included in all the presets...but perhaps should default to that on a new blank parser too, if there;s any way to validate it has been set?

**Comment by cbartondock** [comment]
Yeah that's possible. I should also probably just set it automatically to the default steam location depending on the system (little harder on linux)

**Comment by cbartondock** [comment]
I am unable to replicate this issue in Windows closing for now.
