### ISSUE TITLE
Adds games a second time

### ISSUE THREAD

**Issue by Zzzzz124** [SteamGridDB/steam-rom-manager#221]
Hi there, I noticed steam ROM manager adds games again? I assumed it would check if the game was already there, but it adds another copy to steam. The only problem is if I want to add a new game in the future, will it add copies? is there a setting I have wrong?

Thanks

**Comment by cbartondock** [comment]
It only does this if you have changed something in the parsers. And actually the newest versions shouldn't even do that. Try just removing all in settings and running again; you may have added games with an older version.
