### ISSUE TITLE
[Feature Request] Implement an option to include Adult Content in the image provider search (SteamGridDB)

### ISSUE THREAD

**Issue by SaltyBet** [SteamGridDB/steam-rom-manager#223]
I seems that, by default, searches exclude all content tagged as Adult Content.

The [API page](https://www.steamgriddb.com/api/v2) mentions the following:

> query parameters
> **nsfw** : string
> Set to **_false_** to filter out nsfw, **_true_** to only include nsfw, **_any_** to include both.

**Comment by cbartondock** [comment]
Will do !

**Comment by cbartondock** [comment]
Would you say this should be a global setting or a per parser setting?

**Comment by fenglengshun** [comment]
Not the original poster, but I think this should be a Global Setting - presumably, if user need to pull adult content for one parser and they use multiple parser, then it's likely that they'll want it on for the other parser as well. In addition, if user just wants the complete access regardless of NSFW status, it's easier to just flick it once and forget (or alternatively flick it once and then re-enable once you're done).

That's my two cents on the matter as a visual novel reader at least.

**Comment by cbartondock** [comment]
Added in 2.3.34

@bayazidbh sorry it wound up as a per parser setting. I may add a global default setting later
