### ISSUE TITLE
[Request] Follow .lnk to destination use arguments present in shortcut

### ISSUE THREAD

**Issue by kencinder** [SteamGridDB/steam-rom-manager#227]
Currently using the `Follow .lnk to destination` setting pulls the full executable path out of a shortcut, but drops any additional arguments in it.

I propose pulling these out and being able to stuff them into command line arguments, optionally of course.

Optionally would be best achieved with the use of a variable such as `${lnkArgs}` or `${shortcutArgs}` so users can decide to include them or not.

**Comment by cbartondock** [comment]
Thanks!

**Comment by cbartondock** [comment]
Added in 2.3.36
