### ISSUE TITLE
Command line arguments not being input in to Steam "Launch Options"

### ISSUE THREAD

**Issue by oneder101** [SteamGridDB/steam-rom-manager#230]
I just downloaded this parser today and love it. I stumbled through it and eventually got it all working in Steam via Big Picture, but I got caught up in an issue that I think is a bug. If it's not, please tell me where I went wrong.

For "command line arguments" I used: `--fullscreen --nogui "${filePath}"` as suggested for PSCX2 (pic 1). I loaded my games, set images, and saved app list (pic 2). I was getting errors about the target Steam was trying to launch, so I checked the properties and what I got was the command line arguments in the same target line (pic 3). I had to cut the command line arguments and paste them in the Launch Options text box, then I also had to add "" around the Target and Start In settings in Steam as well (pic 4). This got them all working.

So it seems like the command line arguments are supposed to go in to the Launch Options box but they ended up in the Target box. This happened for each entry.

Parser event log and snapshots included.

[ROM support.txt](https://github.com/doZennn/steam-rom-manager/files/6039982/ROM.support.txt)
![ROM Support1](https://user-images.githubusercontent.com/66270465/109090063-64279680-76e0-11eb-8240-f08bde8d8c1b.png)
![ROM Support2](https://user-images.githubusercontent.com/66270465/109090064-64c02d00-76e0-11eb-8420-b625e7d07030.png)
![ROM Support3](https://user-images.githubusercontent.com/66270465/109090068-6558c380-76e0-11eb-83db-5fa9208dcd90.png)
![ROM Support4](https://user-images.githubusercontent.com/66270465/109090072-6558c380-76e0-11eb-97d2-44666645d12c.png)
![ROM Support5](https://user-images.githubusercontent.com/66270465/109090074-65f15a00-76e0-11eb-8774-f2853dba5760.png)

**Comment by cbartondock** [comment]
Uncheck append arguments to executable
