### ISSUE TITLE
Add Option to fix incorrect titles from SteamGridDB

### ISSUE THREAD

**Issue by mahougomi** [SteamGridDB/steam-rom-manager#235]
Specific example - Sonic the Hedgehog (2006) is incorrectly identified as Sonic the Hedgehog (1991) and thus the wrong assets are downloaded. Can't think of anything off the top of my head, but this is likely an issue with more than just these titles.

**Comment by ZzackKbin** [comment]
For me Soul Blade PSX is Blade & Soul and both game have owna page. Can add option to select game page?

**Comment by kencinder** [comment]
This is not a Steam Rom Manager issue, the date on the games page on steamgriddb is NOT part of the title. I suggest adding images for these locally in the preview window, SRM can only work with what the streamgriddb API returns.

**Comment by cbartondock** [comment]
Potentially we could fix this by allowing the user to change which game it matched with after the fact. I am thinking about the best way to do it - would be a significant rewrite.

**Comment by cbartondock** [comment]
Now possible through the exception manager as of 2.3.28

**Comment by ZzackKbin** [comment]
thx :)
