### ISSUE TITLE
Can't load local images when matching with fileName as the search.

### ISSUE THREAD

**Issue by zthun** [SteamGridDB/steam-rom-manager#237]
Note:  This example use SNES rooms from the GoodSNES set.

When using a local image directory, a glob pattern is required.  I want to have a matching filename png equivalent to the rom smc file.  So I set my pattern to something like this:

C:/Path/To/Pictures/Steam/Grids/SNES/${fileName}.png

So, for example, I have a ROM in my rom directory would have an equivalent image in the pictures directory.

C:/Path/To/Games/SNES/Alien 3 (U) [!].smc
C:/Path/To/Pictures/Steam/Grids/SNES/Alien 3 (U) [!].png

The problem is the rom suffix tag.  These are standard codes for the Good* sets:  https://gist.github.com/ramiabraham/ff41ba74f2b7104ecece

Since I'm using the good dump, [!] tags are in the file name, which cause the image to not be found by the glob matcher.  I tried several different things with this, but finally gave up.  I would prefer not to have to rename and remove all of the suffix codes from my files; a workaround would suffice for me here if I can leave the files immutable.

**Comment by kencinder** [comment]
I would highly recommend moving away from GoodXXX sets to No-Intro, as GoodXXX indexes everything including bad dumps, and are there plenty of issues with their naming, but regardless of that you can use `${finalTitle}.@(png|PNG|jpg|JPG)` to easily get around this.
In the case of your rom and image, you would have this, so you don't have to touch the roms, only the images.

C:/Path/To/Games/SNES/Alien 3 (U) [!].smc
C:/Path/To/Pictures/Steam/Grids/SNES/Alien 3.png

**Comment by cbartondock** [comment]
Closing as Ken's proposed fix should work fine.
