### ISSUE TITLE
Not loading Steam images

### ISSUE THREAD

**Issue by FanderWasTaken** [SteamGridDB/steam-rom-manager#242]
So not all games on Steam have proper images. I made a Steam parser in SRM and when I run it it doesn't get any images that are already there for games, they're all blank (the idea is to add missing assets from SteamGridDB and leave what's already there untouched). Is there any way to fix that? I somehow managed to make it do that a few days ago, now after installing Win11 it no longer works and I have no idea what's going on...

```
# Parser type
····Selected: Steam
# Configuration title
····Steam
# Steam category
····
# Executable
····
····[ ]: Follow .lnk to destination (Windows only)
····[x]: Append arguments to executable
# Command line arguments
····
# Executable modifier
····"${exePath}"
# ROMs directory
····
# Steam directory
····C:\Program Files (x86)\Steam
# "Start In" directory
····
# User accounts
····${***}
····[x]: Skip found accounts with missing data directories
····[x]: Use account credentials
# User's glob
····${title}@(.lnk|.LNK)
# User's glob-regex
····null
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enable Title from Custom Variable
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[ ]: Use fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Image providers
····Selected: 
# Default image
····
# Default tall image
····
# Default hero image
····
# Default logo image
····
# Local images
····
# Local tall images
····
# Local hero images
····
# Local logo images
····
# Local icons
····
····[ ]: Disable current parser
····[ ]: Show advanced options
```

**Comment by cbartondock** [comment]
Can you give me an example of a game on steam that doesn't have artwork? If it's cheap I'll buy it so I can do the debugging to fix this.

**Comment by FanderWasTaken** [comment]
> an example of a game

Well none of the games get their default artwork. Also not all the games show up. Half-Life and Half-Life 2 for example. But again, none of my Steam games show up with an artwork

**Comment by cbartondock** [comment]
You didn't select an image provider.

**Comment by FanderWasTaken** [comment]
> You didn't select an image provider.

It should load images already in Steam, that's the issue - it doesn't...

**Comment by cbartondock** [comment]
No that's not how that works. Those games images are not stored in a way SRM can easily access them. In the steam parser there is a field for default image provider, set it to SteamGridDB.

**Comment by FanderWasTaken** [comment]
How the hell did I manage to make it load default Steam assets last time then o.O
