### ISSUE TITLE
SRM has trouble with "+"

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#27]
@FrogTheFrog  I believe there is a possible bug when SRM tries to find a image for a game title. I uploaded a image for a game that has a "+" in its title. The "+" is necessary because it was included in the actual title of the games. One example of this is "Sonic & Knuckles + Sonic the Hedgehog 2" for the Sega Genesis. This is the image for the title http://www.steamgriddb.com/game/Sonic%20&%20Knuckles%20+%20Sonic%20the%20Hedgehog%202/
Here is the properly encoded "+" symbol: http://www.steamgriddb.com/api/grids/?game=Sonic%20%26%20Knuckles%20%2B%20Sonic%20the%20Hedgehog%202&orderby=date&orderdirection=DESC 
Here is what SRM is doing: http://www.steamgriddb.com/api/grids/?game=Sonic%20%26%20Knuckles%20+%20Sonic%20the%20Hedgehog%202&fields=author,grid_url

thanks @doZennn for helping me with this issue

**Comment by FrogTheFrog** [comment]
Fixed.

**Comment by HEspoke** [comment]
@FrogTheFrog Thanks! glad to be testing this program
