### ISSUE TITLE
Intermittent "No images available" from ConsoleGrid.com

### ISSUE THREAD

**Issue by GrandmasterC** [SteamGridDB/steam-rom-manager#3]
For certain titles (the Mega-Man Battle Network series and others) images are not scraped consistently from ConsoleGrid.come (And aren't found on SteamGridDB.com).  
  
I reproduced this bug multiple times by simply generating a new list a few times. Occasionally the images would be scraped.   
  
Tested with:
"Final Fantasy IV Advance"
"Dragon Ball - Advanced Adventure"
"Mega-Man Battle Network"
"Pokemon Leaf Green"  
  
Using Online Mode & Greedy Search:

![success](https://cloud.githubusercontent.com/assets/26259281/25643175/04367100-2f96-11e7-945c-2098838b156d.png)
Here the image is successfully scraped from ConsoleGrid.com

![fail](https://cloud.githubusercontent.com/assets/26259281/25643188/1b985516-2f96-11e7-868d-7eefedcafa5e.png)
Here the image is unsuccessfully scraped from ConsoleGrid.com

From the Event Log it appears that the bug is due to a timeout error.

**Comment by GHowlett** [comment]
An easy fix to this would be adding "http://retrogaming.cloud" as a more reliable source / API

**Comment by FrogTheFrog** [comment]
@GrandmasterC This is `ConsoleGrid.com` problem. I have to timeout after 2 mins, otherwise it just loads, like forever (made it to 10 mins once, just to test). `ConsoleGrid.com` is "dead" and thankfully, does not host these images.

**Edit**. I'll decrease the timeout and will add few retries just in case.

**Comment by FrogTheFrog** [comment]
@GrandmasterC All providers will now have 40 s timeout and 3 retries.
