### ISSUE TITLE
[Request] Prevent ROM manager from overwriting existing ROMs in Steam Library

### ISSUE THREAD

**Issue by larsflyger** [SteamGridDB/steam-rom-manager#321]
Whenever I add a couple new roms to the relevant rom folder and hit "generate new list" it appears to overwrite the titles already in my library, thus deleting any custom banners and artworks I have for them.

I've yet to find a way to fully circumvent this, and from what I have been able to figure out from various tech support questions there doesn't seem to be an option to force the parser to skip over titles that Steam Rom Manager already detects in the library. I'm sure would be a lot easier to add new ROMs to the library if this were an option.

**Comment by cbartondock** [comment]
There is a setting in SRM to prefer artwork that is already present, `Show current Steam images by default`. Should be enabled by default but I would guess yours is disabled.

**Comment by cbartondock** [comment]
If this is your problem let me know and I will close the issue.

**Comment by larsflyger** [comment]
I am currently away from my Linux setup but I will let you know as soon as I am able to test it, most likely this afternoon. Thanks.

**Comment by larsflyger** [comment]
Hello, this appears to have worked. I don't know why this setting was disabled for me but switching it on has saved my previous custom artwork.

Thanks!

**Comment by maxi1134** [comment]
Similar to this, is there a way to NOT look for existing data? As to minimize calls to the internet.
