### ISSUE TITLE
Its posible ignore some files

### ISSUE THREAD

**Issue by OldMartin** [SteamGridDB/steam-rom-manager#33]
i have some states in some game folders and some sav files and jpg files there its a way to ignore some format files?

**Comment by HEspoke** [comment]
The way that SRM operates is that you define what files will be found by the program. SRM will not find any file type that you do not define. So to answer you question, SRM ignores everything unless you tell it to find something. Just define the file type you want it to find and SRM will do the rest. Below is a picture of an example of a typical SNES file type field within SRM Parser.

![image](https://user-images.githubusercontent.com/26511314/28882241-b011a42a-7778-11e7-97f3-244c848eba31.png)

**Comment by HEspoke** [comment]
I am going to close this issue now, I believe your question was answered. If you want to ask more about this subject please don't hesitate to post on this closed issue. Thanks!
