### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by mdeguzis** [SteamGridDB/steam-rom-manager#34]
Can you please post these? I may assume your app is a docker image, which if so, I know how to build, but including this in your readme would help any others

**Comment by HEspoke** [comment]
As you might already know, the EXE installer is in the releases section of the GitHub and will do everything automatically for the user . As far as instructions on "how to build ", I am assuming that you mean you need to know how to compile the program if you choose not to use the EXE? If this is the case let me know and I can help you out .

-Tyler

**Comment by mdeguzis** [comment]
I am on Linux. I run an external repo for SteamOS under a github repo "SteamOS-Tools". I wish to package this.

**Comment by HEspoke** [comment]
Gotcha, I am mostly a Windows user so that is beyond my realm of knowledge. Wait for @Frogthefrog to take a look at this issue and he can help. Thanks

**Comment by FrogTheFrog** [comment]
@mdeguzis I'm currently styling markdown, after that I'll go and update readme. 

After `npm install` run `npm run build:linux` and it should build for linux. I'm planing to update docker config later as it is not working for some reason right now.

**Comment by mdeguzis** [comment]
If you toss this on npmjs.org, I could use npm2deb to convert the repo code.

**Comment by FrogTheFrog** [comment]
SRM is not really a reusable module/package. Should it really be on npm?

**Comment by mdeguzis** [comment]
Just a suggestion as it would.makw producing a Debian package either. However, of you're willing to work with me on that I will gladly host it on ym repo and a PPA for you.

**Comment by FrogTheFrog** [comment]
@mdeguzis Let's discuss this after I'm finished with 2.1.0 release.

**Comment by mdeguzis** [comment]
Sure np. I'm just happy there is another player in this space after ICE development has frozen.

**Comment by doZennn** [comment]
> **ICE** development has _frozen_.  

_Ba dum tss!_

**Comment by FrogTheFrog** [comment]
@mdeguzis I've updated readme for developers. It basically requires 2-3 commands to build linux binaries/packages. So, what now?

**Comment by mdeguzis** [comment]
I'll take a crack at it today or tomorrow. I'll have to see if I can determine the required files needed after packaging

**Comment by FrogTheFrog** [comment]
I'm closing this issue as it has been resolved.
