### ISSUE TITLE
[Enhancement] Undo on delete

### ISSUE THREAD

**Issue by ChibiChoko** [SteamGridDB/steam-rom-manager#39]
After accidentally deleting a parser I had set up, I think it would be swell to add an undo button after deleting a parser. Just in case.

**Comment by FrogTheFrog** [comment]
What about just a modal window asking you to confirm your action? For all red buttons.

**Comment by ChibiChoko** [comment]
That's an option, though I believe someone in Discord earlier provided a strong reasoning for an undo button rather than a confirmation prompt.

https://alistapart.com/article/neveruseawarning

**Comment by HEspoke** [comment]
I tested the fix that you made concerning the Auto Saving when Testing Parser. It has a undesirable outcome unfortunately. If a user edits the parser and then presses  Test Parser before pressing Save then the user looses all the changes that he made to Test Parser. What I was hoping would happen is that a user could use the Test Parser button as a simulation ground when creating Parser configs. But what happens is that if the user presses Test Parser then he looses all changes made to the parser if he didnt first press Save.
If you cant work out a way to make Test Parser keep the changes in the parser but not permanently save them until the user presses Save then you should revert SRM back to its previous state and make Test Parser save when the Test Parser button is pressed.

**Comment by HEspoke** [comment]
@FrogTheFrog Great job on getting the Test Parser functionality working in a way that allows the user to do a test config on their parser. I like it
