### ISSUE TITLE
[Enhancement] Disable Button for Parsers

### ISSUE THREAD

**Issue by ChibiChoko** [SteamGridDB/steam-rom-manager#40]
So that we can have a parser saved even if it's currently inactive, for whatever reason. (Not working, nothing to add, etc)

Ideally, the button would disable the parser from being run until it was enabled again, but the parser would still be saved in the list.

**Comment by FrogTheFrog** [comment]
You mean the "Enable configuration" button/switch?

**Comment by ChibiChoko** [comment]
Huh, I thought it was a toggle to add extra configurable options in the parser. Whoops.

**Comment by FrogTheFrog** [comment]
Easiest issue ever :D
