### ISSUE TITLE
Generate Applist Error on empty ROM folder

### ISSUE THREAD

**Issue by ChibiChoko** [SteamGridDB/steam-rom-manager#41]
So I discovered if you have multiple parsers, if the last parser/s have an empty rom folder (or find nothing in them/filter all the results out), nothing bad happens and the other parsers run just fine.

However, if any parser that has an empty folder (or finds no files) has a working parser after it, it will stop parsing completely and produce the following error.

"Executing parsers.
Fatal error occurred. See event log for details.
TypeError: Cannot read property 'files' of undefined"

**Comment by FrogTheFrog** [comment]
Solved. Until this bug fix is released, just disable the empty configuration.
