### ISSUE TITLE
Possible bug with steam profile settings

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#42]
I noticed today that if your steam account is not set to have your user name and password saved on the computer then SRM does not recognize that there is a Steam account on the computer. This may not be a bug at all but I just wanted to let you know about it. If there isnt a fix for it then it should be added to a Tool Tip to have this check box in the picture UNCHECKED. Thanks

![image](https://user-images.githubusercontent.com/26511314/29387034-47b6b250-82ac-11e7-905f-4acedad85ba1.png)

![image](https://user-images.githubusercontent.com/26511314/29387326-933ea61e-82ad-11e7-91cd-6375f6a59c6a.png)

**Comment by FrogTheFrog** [comment]
I could get all user directories without account credentials, but then I won't be able to limit configurations to specific accounts or show usernames. I believe I'll leave it as it is and I'll just add warning about credentials. I imagine only a minority uses this setting.

**Comment by FrogTheFrog** [comment]
Ech... I'll just add configuration option whether to use or not to use credentials for retrieving available accounts.

**Comment by HEspoke** [comment]
I agree that this would probably be a minority issue. BUT I was in the mind set of what a user would be doing if he strictly wanted to use the portable version. That type of user might want to not have his steam information saved on a computer that he is trying to sideload his roms/emulators with and loading SRM from a usb stick.

**Comment by HEspoke** [comment]
Thanks for making the changes. Let me know when you have all that in place and I will announce the portable version.
