### ISSUE TITLE
Unsaved parser settings are lost when clicking "Test parser"

### ISSUE THREAD

**Issue by DannyMeister** [SteamGridDB/steam-rom-manager#44]
1. Open a previously saved parser
1. Change settings such as ROMs directory and User's glob
1. Click the "Test parser" button.
1. Click back to the parser you were testing.  All setting changes are gone.

I would expect the behavior would be to leave the modified settings in place.  The primary reason I would ever hit "Test parser" would be to see if my new parser settings work well.  I wouldn't want to have to save my parser settings before I got them right.

If you do allow navigating away without losing parsing settings, I can see how this bug report would actually turn into more of an enhancement.  A more robust save system which shows each modified parser with a * next to its name so that you are aware it has been edited would then make it apparent that it is not yet saved.

**Comment by HEspoke** [comment]
Thank you @DannyMeister for posting this issue. The dev @FrogTheFrog  is a already aware of this issue and I commented on it in issue #39 . He is hard at work with features for SRM and will adjust the undesirable behavior of the Test Parser function regarding loosing unsaved settings when the Test Parser runs. Thanks!

**Comment by FrogTheFrog** [comment]
@HEspoke Let's keep it open until I actually fix this.

**Comment by HEspoke** [comment]
Ok, didn't known how you felt about having two issues open that address identical issues. I'll leave identical issues open in the future .
