### ISSUE TITLE
[Enhancement] Seperate "Rom Directory" With Steam "Start In"

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#45]
After diving deep into MAME compatibility for SRM. There is one request that I have currently that would make SRM more compatible with MAME. SRM should have a line added to the Parser when Show Advanced Options is turned on. That line should be "Start In". This is the start in directory for steam and is required to start in the MAME home folder as pictured. 
![image](https://user-images.githubusercontent.com/26511314/29499479-9d0648ce-85e0-11e7-90e3-09fe45f2b02e.png)

Then when the above line is utilized then the "ROM Directory" line will just be for looking for the ROM files exclusively and will not have anything to do with altering the "Start In" line for non steam shortcuts. 
![image](https://user-images.githubusercontent.com/26511314/29499476-82a488ce-85e0-11e7-89f1-11771f8d4db7.png)

**Comment by FrogTheFrog** [comment]
@HEspoke Almost done with #44 and #39. Will add a field for custom "Start In" directory. Anyway, FYI "ROM Directory" has nothing to do with "Start In". By default, executable directory is used for "Start In".

**Comment by FrogTheFrog** [comment]
@HEspoke Now that I think about it, I don't see why you need it as "ROM Directory" has nothing to do with this.

**Comment by HEspoke** [comment]
@FrogTheFrog Its because I had to use batch files so that I could rename the files so that they could be fuzzy matched. By doing this I cleared the EXE field in the parser so that the batch could run properly. When I cleared the EXE it shows a Start In Field that is other then the MAME EXE home directory because my rom directory where the batch is in a different folder then my mame folder, I have a seperate ROM location that I store all my ROMS. MAME has some quirks that are VERY unique. I think the most practical way to make MAME work reasonably with SRM is if SteamGridDB had the ability to have their ALTERNATE titles be matched with the title that also gets fuzzy match. For Example, the match for Killer Instinct - Arcade should be matched when the filetitle of kinst (an alternate title for Killer Instinct - Arcade) is found in the Rom Directory. But the dev for steamgrid has this on the backburner. 
Solution: If you change the title for the Executable line in the parser to "Executable of Emulator or Start In Directory". And then change SRM so that it will still run the parser if only a directory is filled in for this line WITHOUT a exe.

**Comment by FrogTheFrog** [comment]
@HEspoke I'll add "Start In" directory field, your second suggestion makes everything too complicated

**Comment by FrogTheFrog** [comment]
Added new option for "Start In" directory.

**Comment by FrogTheFrog** [comment]
What didn't make sense is why did you need it, until you explained it :D
