### ISSUE TITLE
Build: loader-utils version conflict

### ISSUE THREAD

**Issue by DannyMeister** [SteamGridDB/steam-rom-manager#51]
I get lots of build errors similar to this one:

> Module build failed: TypeError: loaderUtils.getOptions is not a function
>     at Object.module.exports (F:\Users\Danny\Documents\GitHub\steam-rom-manager\node_modules\nested-require-loader\index.js:42:53)
>  @ ./shared/lang/english/langData.ts 181:28-58
>  @ ./shared/lang/index.ts
>  @ ./shared/lib/language-manager.ts
>  @ ./shared/lib/index.ts
>  @ ./renderer/components/theme.component.ts
>  @ ./renderer/components/index.ts
>  @ ./renderer/app.module.ts
>  @ ./renderer/app.ts

It seems you have some 3rd party packages which depend on some old versions of loader-utils package.  The nested-require-loader is fetching these older versions and it is taking precedence on newer packages that call a new getOptions() function that is required as of version 1.0.0 of loader-utils.  I hate dependency hell. 😄 I tried forcing the latest version of loader-utils by including it in packages.json, but the old one is still being pulled in anyways.  I'm too green with npm package management to figure this out so far.

**Comment by DannyMeister** [comment]
Gist of me trying to build after your latest push:

https://gist.github.com/DannyMeister/8f99ef83f922fc6adf3972542e06140a

**Comment by FrogTheFrog** [comment]
Try now with package-lock.

**Comment by DannyMeister** [comment]
That, along with clearing out previously downloaded packages, did the trick.  Thanks!
