### ISSUE TITLE
[Enhancement] Version Details

### ISSUE THREAD

**Issue by HEspoke** [SteamGridDB/steam-rom-manager#52]
I have had users ask me over the past weeks where the version is in SRM. I tell them that its in the Log and problem solved, but I would like this to be easier for a user to find in a logical place. Could you put the version in a persistent place like in the Settings option as well as the Log? 

- In the Settings option, so that the user can see it in what would be a logical place for a typical user and possibly find it on their own. 

- In the Log, so that it will be posted when they have issues and they post the entire log for tech support.

- Have the version also show the type of SRM package it is along with the version number? For example, Portable vs Installed. Windows vs Linux? that would help us with troubleshooting because we can just see it in the Log instead of asking more questions. Thanks!

**Comment by HEspoke** [comment]
@FrogTheFrog Looks like you implemented everything with the feature request except for the 3rd bullet point. Great Work.

- Have the version also show the type of SRM package it is along with the version number? For example, **Portable vs Installed. Windows vs Linux?** that would help us with troubleshooting because we can just see it in the Log instead of asking more questions. Thanks!

we talked about the Portable vs Installed. Windows vs Linux feature and discovered that it was not displaying proper information there (not at the fault of SRM). Is this something you are still going to pursue in the next release or should we close the Issue?

**Comment by FrogTheFrog** [comment]
@HEspoke Let's keep it open. I'll forward this issue to Electron developers sometime in the future.

**Comment by cbartondock** [comment]
Fixed in my PR #176

**Comment by cbartondock** [comment]
@HEspoke this is fixed as of 2.2.25, please verify and close the issue.
