### ISSUE TITLE
Removing brackets doesn't remove for some games.

### ISSUE THREAD

**Issue by Hunk4TH** [SteamGridDB/steam-rom-manager#54]
Hello there!

The remove brackets feature is great and does do what it's supposed to however it doesn't remove them from some games. Also would it be possible to exclude removing (Disc 1) brackets? :) 

Thanks!

**Comment by FrogTheFrog** [comment]
Hello,

SRM removes brackets only for fuzzy matching. If fuzzy matching fails, SRM continues working with extracted title, thus it will look like it did not remove anything.

To completely remove brackets, you need to use `Glob-regex` parser. Then, for example, use the following glob to remove `(...)` and `[...]`: `${/(\s*?\(.*?\)|\s*?\[.*?\])/|}.iso`.

To keep `(Disc 1)` and similar brackets, use this monstrosity `${/((?!(?:\s*?\(Disc\s*?[0-9]\s*?\)))\s*?\(.*?\)|\s*?\[.*?\])/|}.iso`. Keep in mind that keeping `Disc` might prevent you from finding images.

**Comment by FrogTheFrog** [comment]
SRM 2.2.0-10 now supports nested variables. This will allow to do this:

![this](https://user-images.githubusercontent.com/22381748/31019371-299c6c5c-a538-11e7-9d2f-7bd90643e440.png)
and get this:
![this2](https://user-images.githubusercontent.com/22381748/31019379-2e13e814-a538-11e7-8da8-73158896df9b.png)

With 2.2.0-10 if fuzzy matcher does does not remove brackets, you can now remove them manually basically anywhere.
