### ISSUE TITLE
User selection does not seem to be effective

### ISSUE THREAD

**Issue by felipecrs** [SteamGridDB/steam-rom-manager#544]
I share my computer with two other Steam accounts, but I only want SRM to add entries into my main user.

Selecting the user in the settings does not seem to help in anything, SRM still offers to add my games to all Steam accounts.

https://user-images.githubusercontent.com/29582865/236462999-f17e5e7f-bf60-4fdf-a47f-ab001b25ad0d.mp4

Maybe I'm missing something... v2.4.15, Windows 11.

**Comment by cbartondock** [comment]
Yeah you're missing something, you also need to set the user accounts field to `${${accountsglobal}}` in the parsers. This will be the default in the future but not yet.

**Comment by cbartondock** [comment]
The field is also planned to become mandatory, and EmuDeck will set it automatically.

**Comment by felipecrs** [comment]
Thank you! But maybe I'm still missing something? Fixing the parsers does not seem to help in anything:

https://user-images.githubusercontent.com/29582865/236464533-584b334e-b4fd-420f-aa02-3e540fe0c4dd.mp4

**Comment by cbartondock** [comment]
You didn't save the changes to the parser. Note the yellow dot next to the name.

**Comment by felipecrs** [comment]
Oh man. My bad! Thank you!

**Comment by felipecrs** [comment]
It worked nicely by the way.

**Comment by cbartondock** [comment]
Great! It's a new feature so that's good :).

**Comment by felipecrs** [comment]
> The field is also planned to become mandatory, and EmuDeck will set it automatically.

Hey @cbartondock, I was wondering if you have any news about it. I was testing EmuDeck and SRM again today and ran into this "issue" again.
