### ISSUE TITLE
Option to NOT add titles where box art wasn't found

### ISSUE THREAD

**Issue by FreeSoftwareServers** [SteamGridDB/steam-rom-manager#56]
I have way to many roms downloaded in packs, I attempt to clean the titles, but some i just dont really care lol. I'd be happy to just only add the ones that SRM finds box-art for.

**Comment by FrogTheFrog** [comment]
I'm slowly rewriting my "VDF manger". In the end, one function will handle generated list with various options for saving entries. I'll make sure to throw this in too.

**Comment by ghost** [comment]
I'd like this to. I have to many ROMS to make the selection myself or  add all to Steam. :)

**Comment by Tenome** [comment]
I'm going to piggy-back off this post since my request is basically the same. Sometimes, SRM identifies the wrong game when generating the app list. I just want the option to delete any wrong ones.

**Comment by cbartondock** [comment]
@Tenome you can already do that using the exception manager

**Comment by cbartondock** [comment]
Fixing matches and excluding apps are super easy as of 2.4.5 and 2.4.6 so I am closing this as completed.
