### ISSUE TITLE
Command Line Arguments for Automation

### ISSUE THREAD

**Issue by ShadowEO** [SteamGridDB/steam-rom-manager#58]
Since I noticed the functionality isn't available, I figured I'd add an enhancement request to the list, I'd implement it myself and send a pull request, but I'm afraid I'm not any good with JavaScript/TypeScript/Node.js (if it were any other language, would be more than happy to, but I digress..)

Essentially, my enhancement request is this, I'd like to be able to create a batch file or scheduled task (similar to what is semi-possible with Ice) so that I can drop ROMs into their respective folders, run the created batch file/script (or even make it run every hour or so to pick up new ROMs) and have it automatically add those games according to the rules I had set up in the application's GUI.

I completely understand if this is out of the scope of the project as it is right now, just would like to automate it without trying to write some shim for it through AutoIt since I'm not sure that Window Control matching would work in an electron app anyway.

**Comment by FrogTheFrog** [comment]
I'll try to add this feature once all other enchantment issues closed and some other features are added.

**Comment by chasebolt** [comment]
I also am interested in this. Was going to use this in a project having to backtrack on this because it can’t be automated yet.

Great project and subscribing to this for future updates. Thanks!

**Comment by Teutonic84** [comment]
I'd also like to see this added. I currently use ice with command line arguments so i can automate importing to steam with batch files. I think this is actually a pretty important feature even if it doesn't seem that way currently. I'm sure i'm not the only one that can't make the jump from ICE to this because of no command line arguments. As soon as it's added, i'll be downloading and installing steam rom manager, but until then, i'm not touching it.

**Comment by Godsbane** [comment]
From Emudeck land, I could see this being extremely useful in our "Easy" mode. Would be nice to be able to at least auto import the base emulators at the end of the script.

**Comment by cbartondock** [comment]
Yeah for sure. It's coming, but there are two ways of attacking the problem:
* One is using yargs to call functions of the fully spun up gui behind the scenes. This is less work (probably) but will have a significant cost in terms of delay/ time for commands to execute.
* The other (suggested above by @Maykin-99) is to properly separate the backend from the front-end. This is an absolutely crushing undertaking (SRM's code base is... big), but is ultimately the more elegant solution.

So I'm punting on this one for the time being, maybe some time in the mid term future I'll give it a go. In the meantime I am tackling other problems and adding other features, but this is on my mind. If someone wants to take it on I will absolutely merge the PR.

**Comment by rkr87** [comment]
Just dropping in to say this is something I'd really like to see implemented too.

**Comment by sairuk** [comment]
Also after this functionality, thanks

**Comment by cbartondock** [comment]
Now in master, will be in incoming 2.4.0 release.
