### ISSUE TITLE
Non-portable Windows Installers Crash (2.2.3 and 2.2.2)

### ISSUE THREAD

**Issue by lahma0** [SteamGridDB/steam-rom-manager#59]
I just thought I would make you aware that the last version that has a working Windows installer is v2.2.1. Both v2.2.2 and v2.2.3 crash when trying to run the non-portable Windows installer. I tried them on both my local Windows 10 x64 Enterprise box as well as a fresh Windows 10 x64 Pro VM and a fresh Windows 7 x64 Pro VM. The portables work fine.

**Comment by FrogTheFrog** [comment]
It seems to be related to https://github.com/electron-userland/electron-builder/issues/2134. Will update dependencies tomorrow and recompile 2.2.3

**Comment by FrogTheFrog** [comment]
@lahma69 Can you try installer now?

**Comment by h-wb** [comment]
I had the same problem, and I confirm it is now working, thank you.

**Comment by lahma0** [comment]
Sure! I will give it a shot as soon as I get home.

**Comment by FrogTheFrog** [comment]
It seems to be fixed, so I'm closing this.
