### ISSUE TITLE
Saving List Breaks shortcuts.vdf file

### ISSUE THREAD

**Issue by GHowlett** [SteamGridDB/steam-rom-manager#6]
Not sure whats wrong with it, but when I try to save my shortcuts using the ROM manager, all Non-Steam Game shortcuts disappear from steam and I have to revert to the backup. I've attached the broken vdf file and original backup.

**Comment by GHowlett** [comment]
Github wasn't letting me upload the zip, so I renamed it as a txt. Rename it back to extract the files.

[shortcuts.zip.txt](https://github.com/FrogTheFrog/steam-rom-manager/files/972652/shortcuts.zip.txt)

**Comment by FrogTheFrog** [comment]
Now that `shortcuts.vdf` parser is fixed, I'm giving my VDF manager a total rewrite as I noticed "holes" in my logic. Many of them were fixed but many may still remain.

**Comment by FrogTheFrog** [comment]
@GHowlett could you try out the new v1.2.0 pre-release?

**Comment by GHowlett** [comment]
1) The shortcuts are no longer being corrupted, but about half of the dolphin shortcuts are appearing with no image (just the default dolphin exec image), and no name. Upon examining the command line arguments of the shortcut, they appear correct, but starting the shortcut is not launching the correct game. For example, if I start the shortcut with zelda as the argument, a different game starts. The shortcuts that do have names do not have this issue.

2) The load time of images seems to be much longer now, but that's not a big issue.

3) The retrogaming.cloud API is responding with a failed 429 HTTP response:
Failed to retrieve some image urls for "Mario Kart Wii"
Response with status: 429 Too Many Requests for URL: http://retrogaming.cloud/api/v1/game/2488/media (http://retrogaming.cloud/api/v1/game/2488/media)
Response with status: 429 Too Many Requests for URL: http://retrogaming.cloud/api/v1/game/2517/media (http://retrogaming.cloud/api/v1/game/2517/media)
Response with status: 429 Too Many Requests for URL: http://retrogaming.cloud/api/v1/game/13407/media (http://retrogaming.cloud/api/v1/game/13407/media)

**I attached the half-working shortcuts.vdf**
[shortcuts.zip.txt](https://github.com/FrogTheFrog/steam-rom-manager/files/981326/shortcuts.zip.txt)

**Comment by FrogTheFrog** [comment]
1. Images don't show because there is no name for a game. It seems that `shortcuts.vdf` has `AppName` and some of them are empty. I do not use it anymore, instead `appname` is used now. It could be remnant from previous releases. Could you try manually removing entries with missing titles and adding them again?

2. Blue circle or green circle?

3. Can't really do anything about it. I could filter out those errors, but then what's the point of them?

**Edit**

3. Error will now show only if it still fails after 3 retries. This should eliminate most of those errors, because most of them actually succeed retrieving data on second try. (It will be in the next release)

**Comment by FrogTheFrog** [comment]
@GHowlett Added support for `AppName`. I can now be changed, but all new entries should have `appname`. Could you restore backup and try it out on v1.2.1?

**Comment by FrogTheFrog** [comment]
@GHowlett I talked with the owner of `retrogaming.cloud` and we will try to address `429 Too Many Requests` somehow. Also, could try try v1.2.1, or are you busy?

**Comment by FrogTheFrog** [comment]
Everything seems to be addressed in latest release, so I'm closing this issue.
