### ISSUE TITLE
Error Encountered While Reading User Configurations - updating to 2.2.3 from 2.0.1

### ISSUE THREAD

**Issue by CyricPL** [SteamGridDB/steam-rom-manager#60]
I'm trying to update versions after not doing so for a few months, but I am receiving this error and none of my parsers show up in 2.2.3. When I revert to 2.0.1 all is there, no problem. I'd rather not take the time to rebuild the parsers if I can avoid it; is this a known issue?

**Comment by FrogTheFrog** [comment]
Could you post this error? From the event log.

**Comment by FrogTheFrog** [comment]
@CyricPL Could you also upload your configuration file somewhere?

**Comment by CyricPL** [comment]
Here is the event log:

One or more saved parser configurations are invalid!
Permanent configuration saving is disabled until this issue is resolved.
Try to manually fix errors yourself (file - C:\Users\John\AppData\Roaming\steam-rom-manager\userData\userConfigurations.json)
or seek help on github or our official discord channel: 
[0]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]
[1]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]
[2]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]
[3]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]
[4]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]
[5]:
    [
        {
            "keyword": "enum",
            "dataPath": ".parserType",
            "schemaPath": "#/properties/parserType/enum",
            "params": {
                "allowedValues": [
                    "Glob",
                    "Glob-regex",
                    ""
                ]
            },
            "message": "should be equal to one of the allowed values"
        }
    ]

**Comment by CyricPL** [comment]
Here's the config file: https://www.dropbox.com/s/8sqfvrizq51sm6v/userConfigurations.json?dl=0

**Comment by FrogTheFrog** [comment]
@CyricPL Check out v2.2.4. Also, by default new configurations have image providers set to `None` (yours is also considered as new in this case). Be sure to enable them.

**Comment by CyricPL** [comment]
Good now; thanks!
