### ISSUE TITLE
Add window border, or option to enable one or alter background color.

### ISSUE THREAD

**Issue by kencinder** [SteamGridDB/steam-rom-manager#61]
When using with a black background or other dark windows, it's often hard to locate the edge of SRM's window.
A thin raised border would work well, or the option to enable one. The option to change the background color of SRM, outside of the preview pane, could also help.

**Comment by FrogTheFrog** [comment]
There was a feature once that allowed to change every color in UI. It was pain in *** to keep supporting. I am, however little by little reducing colors to a specific palette. Once that is done, I'll re-enable that feature.

**Comment by cbartondock** [comment]
Fixed by new themes
