### ISSUE TITLE
[Enhancement] Add a "default image" field in the parser configuration.

### ISSUE THREAD

**Issue by zenovalle** [SteamGridDB/steam-rom-manager#64]
One can select a default image to use when no image can be found from providers or local pool. It is nice, for example, having something like this: https://imgur.com/uZgqg as a custom default image. The field could use glob and the variables identified by the parser.

**Comment by zenovalle** [comment]
Yes, I can do that, I didn't think about combining it, thanks. The only con: it always takes the local image first, so if a game has no local image, but it has images from providers, it always gives the default and then I have to change it manually to one of the other images. No great problem, but it is a long work when you have a massive game list.

**Comment by FrogTheFrog** [comment]
Very well, I'll add a separate field for default image. It will work like local images except that it will only use first result AND it will be shown only when there are no images. If Steam image is available, it will be placed after Steam image, so you will have 2 images to choose from.

**Comment by zenovalle** [comment]
Sounds good!

**Comment by FrogTheFrog** [comment]
@zenovalle Try 2.2.9. If it works, close this issue.

**Comment by zenovalle** [comment]
It works, thank you!
