### ISSUE TITLE
Add local image icon

### ISSUE THREAD

**Issue by zenovalle** [SteamGridDB/steam-rom-manager#65]
I press the icon in the preview and then select a local file but... nothing happens. How it should be supposed to work? Installed on WIN 10. Thanks.

**Comment by FrogTheFrog** [comment]
You mean Icon or Grid image? If you meant Icon, I did not add a button for it (honestly, I forgot), however if you meant grid image, I gets added at the end of available images if the image is valid (total image number should increase).

**Comment by zenovalle** [comment]
Sorry, my comment wasn't clear, I mean this icon:
![image](https://user-images.githubusercontent.com/19671088/32801871-a6ed1ab6-c97e-11e7-821e-a239f81cf6de.png)
to add a new Grid image, but the list does not increase, I'm using PNG images 460 x 215 pixels long.

**Comment by FrogTheFrog** [comment]
Can you send me this image, you're trying to add?

**Comment by FrogTheFrog** [comment]
And also give me a full filename.

**Comment by zenovalle** [comment]
Here they are: https://drive.google.com/open?id=1tZSx8KUx1FJLwG2TdBte2YUjnIBoWyt2

**Comment by FrogTheFrog** [comment]
@zenovalle Do you see a file selection window after clicking on that icon/button?

**Comment by zenovalle** [comment]
Yes, and then I select the image, Open, but nothing happened.

**Comment by FrogTheFrog** [comment]
@zenovalle Can you try double clicking on image file instead of clicking open?

**Comment by FrogTheFrog** [comment]
I think I have found a bug in Angular. Need to work my way around it.

**Comment by FrogTheFrog** [comment]
This issue might be related to older chromium version that Electron is using. Once a new update is released, I'll upgrade ASAP, for now double clicking is the way :/

**Comment by zenovalle** [comment]
Double click is not working. I'm thinking to restart from scratch and trying with two or three ROMs. Where do I find the configurations files? I want to clean all. Maybe is something related with some WIN 10 permission and I have to start the app in Administrator Mode?

**Comment by FrogTheFrog** [comment]
Administration mode is not required. Everything is in `%APPDATA%\steam-rom-manager`. Can you try portable version? See if it works with that.

**Comment by FrogTheFrog** [comment]
I believe, I found an issue in my logic. Will fix it ASAP and build new release which will also have default image option.

**Comment by FrogTheFrog** [comment]
@zenovalle Check out 2.2.9.

**Comment by zenovalle** [comment]
It works now, thanks!
