### ISSUE TITLE
Just copied and pasted from discord regarding numeric categories

### ISSUE THREAD

**Issue by klepp0906** [SteamGridDB/steam-rom-manager#68]
I have an atari 7800 set that i have the category set to be named 7800.  This worked fine previously.

I just had to re add all my shortcuts due to a corrupt vdf and as part of the troubleshooting (unsure if related or not) I updated SRM.

it now wont add a 7800 category, I assume since its purely numeric.  All other parsers add respective categories fine but none are purely numeric.  It places the 7800 as "uncategorized".

Figured id let ya know, for now ill just change the category name

**Comment by FrogTheFrog** [comment]
Fixed
