### ISSUE TITLE
Option on Preview to Save chosen image

### ISSUE THREAD

**Issue by ChibiChoko** [SteamGridDB/steam-rom-manager#69]
Basically, on the preview page after generating the applist (and selecting images from the available options) add a save button that will default to the selected local images path and default to using ${title}, so that whenever deleting the entire shortcuts.vdf is necessary to prevent duplicates, reselecting images is a lot faster as long as local images are set up.

**Comment by cbartondock** [comment]
Implemented in 2.3.0
