### ISSUE TITLE
Certain Titles Cause Fuzzy Title Matching to Hang

### ISSUE THREAD

**Issue by SkyNinja** [SteamGridDB/steam-rom-manager#7]
As the title says, certain game titles cause the fuzzy title matcher to hang. Specifically, it seems to be an issue with titles that have multiple similar matches, but nothing exact or even close. Titles I've seen cause this are Ratchet & Clank, Fatal Frame, and Destroy All Humans!. The titles list is missing these games, but features multiple sequels to each.

**Comment by FrogTheFrog** [comment]
@SkyNinja It was a simple bug and will be fixed in latest release. However, I can't really do about false matches. I could add a fix for these 3 entries to be skipped, but then it would break matching for others.
