### ISSUE TITLE
Local images don't always add. Restarting sometimes fixes it short term.

### ISSUE THREAD

**Issue by NOFUNEVER** [SteamGridDB/steam-rom-manager#71]
In instances where I have multiple ports of the same game for different consoles I like to use the system specific box art to help differentiate them from one another. Telling PC/N64/Saturn versions of Quake, QII and Doom apart for example. However sometimes the new banner option doesn't pop up after adding it from local files. If you restart the application over and over eventually you'll get the picture to load as one of the available options in the list. For the above examples of quake 1,2 and doom where I used stock options for the PC versions and custom box art for the saturn and N64 variants I had to restart Steam Rom manager 20+ times before I was able to get the local art to show as an available option after adding it in the browse file menu. In another example i've been trying for about 10 minutes to add local box art for GoldenEye(not showing up in in databases strangely) to no avail. It seems random when it wants to work. I know its not unsuitable jpegs being the issue because they all work eventually...

**Comment by FrogTheFrog** [comment]
@NOFUNEVER You're adding local images via parser or manually?

**Comment by NOFUNEVER** [comment]
This is adding local images manually. Out of 260 games only a small handful of games needed local images (basically the ones listed above and tomb raider ports) so at the time it seemed simpler to add them manually rather than going through and editing all my parsers & renaming the local images. I eventually got them all working manually last night just around the time I decided I should do what I was trying to avoid and just set my parsers up to do it automatically so as to avoid further headaches. However as all my games were working I never tested to see if parsing was adding local images successfully or if that was bugged as well.

**Comment by FrogTheFrog** [comment]
@NOFUNEVER You're using 2.2.10, right? If, not then it will be a very hard bug to replicate :/ . I'll add logging in future release.

**Comment by NOFUNEVER** [comment]
I just installed the program very recently, was unaware their had been multiple revisions since. I was on 2.2.7. Installing now and testing. Will get back to you.

**Comment by FrogTheFrog** [comment]
There was an issue related to this which was fixed in 2.2.9

**Comment by FrogTheFrog** [comment]
@NOFUNEVER Is it working for you?

**Comment by NOFUNEVER** [comment]
my apologies for the late reply. Works as expected after updating. Any chance this will be expanded to cover games run by other launchers? I know steam already makes it pretty easy to load up origin games but it would be nice if this would automate it all including banner images.

**Comment by kencinder** [comment]
@NOFUNEVER It's pretty hard for SRM to know which EXE in PC games to use/add, some have multiples for config/SP/MP. Some are also located different levels deep in a folder, such as inside a "BIN" folder where others are right in the root of the games folder.
Just a cursory look at the idea of it, and it looks like a nightmare to me, to get SRM to handle what's in your Origin/UBI game folders.

It may be possible to have your glob search for EXE recursively and use the custom variables feature in SRM to only add certain EXEs in a JSON and give them a Title.

**Comment by FrogTheFrog** [comment]
As @kencinder said it would be difficult to do and there are no plans for it in the future.

**Comment by dotbanana** [comment]
I have the same problem with Steam Rom Manager on SteamDeck.  
I have couple modded Roms that i added into Steam but it doesn't matter
what local image i choose in the Parser-Preview, he always just takes the default one and there is no way to distinguish those without opening it.
![steambug](https://user-images.githubusercontent.com/22258372/174418088-b0c9c163-76ff-4bca-a91d-88b7f85ffe5c.png)

**Comment by SkilledAlpaca** [comment]
I am also having the same issue above as @dotbanana on my SteamDeck.
