### ISSUE TITLE
[Error] Cannot find module '7zip-bin-linux'

### ISSUE THREAD

**Issue by ArtBIT** [SteamGridDB/steam-rom-manager#72]
When running `npm run build:linux` (after `npm run build:dist`) I get the [following npm error](https://github.com/FrogTheFrog/steam-rom-manager/files/1510079/npm.error.txt):
```
Cannot find module '7zip-bin-linux'
```
After manually installing the required package (`npm i 7zip-bin-linux`) and running `npm run build:linux`, then it completes successfully.

**Comment by FrogTheFrog** [comment]
It's a problem with npm. Sometimes it just decides not to install `electron-builder` dependencies. If I remember correctly, using `npm install` 2 times should fix it.

It's not really a problem with SRM, so I'm closing this.
