### ISSUE TITLE
Steam Rom manager is not adding games

### ISSUE THREAD

**Issue by louie123456789** [SteamGridDB/steam-rom-manager#73]
Everytime i click generate app list the app list doesnt get generated i have steam closed and it still doesnt get generated 

All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
Testing "WII U" parser (SRM version - 2.2.10).
 
Found 1 available user account(s):
  tailsrules723 (steamID64: 76561198353920607, accountID: 393654879)
 
 
Failed to match:
[1/3]: E:\emulator games\Wii U\Mario & Sonic at the Sochi 2014 Olympic Winter Games [AURE01]\code\app.xml
[2/3]: E:\emulator games\Wii U\Mario & Sonic at the Sochi 2014 Olympic Winter Games [AURE01]\code\cos.xml
[3/3]: E:\emulator games\Wii U\Mario & Sonic at the Sochi 2014 Olympic Winter Games [AURE01]\code\urals.rpx
 
Parser test is completed.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.

**Comment by FrogTheFrog** [comment]
@louie123456789 What's your `User's glob`?

**Comment by louie123456789** [comment]
```
# Parser type
····Selected: Glob
# Configuration title
····WII U
# Steam category
····
# Executable
····C:\Users\Ryane\Documents\Programs\cemu_1.11.0\Cemu.exe
# Executable modifier
····"${exePath}"
# ROMs directory
····E:\emulator games\Wii U\Mario & Sonic at the Sochi 2014 Olympic Winter Games [AURE01]\code
# Steam directory
····C:\Steam
# "Start In" directory
····
# User accounts
····
····[ ]: Skip found accounts with missing data directories
····[x]: Use account credentials
# User's glob
···· ${title}
# User's glob-regex
····null
# Title from custom variable
····
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
····[ ]: Enabled
# Title modifier
····${fuzzyTitle}
# Fuzzy matching
····[x]: Use fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Command line arguments
····-f -g "${filePath}"
····[x]: Append arguments to executable
# Online image query
····${${fuzzyTitle}}
# Image pool
····${fuzzyTitle}
# Image providers
····Selected: 
# Default image
····
# Local images
····
# Local icons
····
····[ ]: Disable current parser
····[x]: Show advanced options
```

**Comment by FrogTheFrog** [comment]
@louie123456789 There is a space before `${title}`, remove it. Also, you might want to use `${title}/*/*.rpx` for a glob.

**Comment by louie123456789** [comment]
i still get the same error 
Testing "WII U" parser (SRM version - 2.2.10).
 
Found 1 available user account(s):
  tailsrules723 (steamID64: 76561198353920607, accountID: 393654879)
 
 
Parser test is completed.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.

 i still need my rpx files since cemu relies on them

**Comment by FrogTheFrog** [comment]
@louie123456789 Set ROMS directory to `E:\emulator games\Wii U`

**Comment by louie123456789** [comment]
Done But i still get the same thing, With an older version i didnt have this issue. Could it because i reinstalled windows

All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.

**Comment by FrogTheFrog** [comment]
@louie123456789 No, could you reach me on discord?

**Comment by louie123456789** [comment]
i have discord

**Comment by FrogTheFrog** [comment]
Reach me with `FrogTheFrog#1801`
