### ISSUE TITLE
Please Close Steam While Steam Not Running?

### ISSUE THREAD

**Issue by physiks2017** [SteamGridDB/steam-rom-manager#74]
Hi,

I don't know exactly how to work the Steam ROM Manager, but I got the config to test successfully after looking at a guide that was completely in Portuguese, however, when I click on "Generate apps list", it says "Please Close Steam," even though it is not running. Could I get some help with standard config as well as the closing Steam issue?

Config file:
Parser Type: Glob
Config Name: Gamecube
Steam Category: ${Nintendo Gamecube}
Executable: E:\SteamLibrary\Emulator\RetroArch\RetroArch.exe
ROMs: E:\SteamLibrary\Emulator\ROMs\GameCube\
Steam Directory: C:\ProgramFiles\Steam\
User's Glob: ${title}.@(iso|gcm) QUESTION: Are these the extensions?
Command Line Arguments: --batch --exec "${filePath}
Image Providers: Retrocloud

**Comment by FrogTheFrog** [comment]
Hey,

It is only an annoying reminder to close Steam **if** it is running. Ignore it if you have your Steam closed.

For `${title}.@(iso|gcm)` question, yes - `iso` and `gcm` are extensions. `@(...|...)` means "one of". Also, I believe you'll want `-L cores${/}YOUR_CORE.dll "${filePath}"` for command line arguments.

**Comment by kencinder** [comment]
@FrogTheFrog This comes up almost daily on Discord, perhaps you could bold the IF part, or otherwise indicate somehow that it's only a reminder?
