### ISSUE TITLE
Problem with preview

### ISSUE THREAD

**Issue by Pasturegrownpotato** [SteamGridDB/steam-rom-manager#78]
I set up the parser correctly and everything, and I have Steam closed, but when i go to generate the app list, it tells me to close Steam, yet it is closed. Please help, the download link for ice is down and I really need a rom manager for steam.

**Comment by OldMartin** [comment]
Do you already try to close steam via Task manager?

**Comment by marioandluigi878** [comment]
Same problem here, even checked task manager, and CAN comfirm it is closed

**Comment by FrogTheFrog** [comment]
@Pasturegrownpotato It is only a nagging reminder. I see that it causes a lot of confusion so I'll have to come up with some other way of warning people.

**Comment by Pasturegrownpotato** [comment]
Ah, thanks. Was a bit confused at first. Besides that great software, easy to set up, nice UI. Thanks again for the help.
