### ISSUE TITLE
App Stuck Off Screen

### ISSUE THREAD

**Issue by FeralRants** [SteamGridDB/steam-rom-manager#79]
Updated to the latest version and when the program opens it is stuck on offscreen. Have tried changing the resolution of my monitor to see if that would reset the position, have tried snapping it to the edges of the screen using keyboard commands and so far nothing has worked.

**Comment by FrogTheFrog** [comment]
Could you try deleting `%APPDATA%\steam-rom-manager\userData\window-state.json` file?

**Comment by FeralRants** [comment]
That worked! 
  Thank you.
