### ISSUE TITLE
Add steamcontrollerdb.com support to auto download configurations

### ISSUE THREAD

**Issue by juanrodgil** [SteamGridDB/steam-rom-manager#8]
Not an issue, it's rather an option that I think could be very useful.

So, when you add a not steam game, it search in steamcontrollerdb to fetch for a valid configuration for each game (similar to how it is done with the images)

https://www.steamcontrollerdb.com/home/about

**Comment by FrogTheFrog** [comment]
@juanrodgil Is this really needed? I believe that Steam uses game title to search for configurations uploaded by community. Most people use fuzzy matching and are forced to stick to one title (hopefully the correct one). Thus, if one of them uploads configuration, others can download it. I've already seen a bunch of new configurations that were not there until I released this app.

**Comment by juanrodgil** [comment]
Okay. Then as you say, it might not be necessary
