### ISSUE TITLE
Can't get RetroArch to work in Steam Big Picture 

### ISSUE THREAD

**Issue by s1h4d0w** [SteamGridDB/steam-rom-manager#80]
Hi there,

I've been googling for over an hour now and am yet to be able to boot up a game through RetroArch. After a lot of searching (and a bit of stupidity on my part in missing some key documentation) I should have my PSX and SNES emulator set up correctly.

However, when I start a game in Big Picture it simply goes to an empty dark blue screen (within BP) and then returns to the game page on Steam. These are my settings (copied from the docs):

![image](https://user-images.githubusercontent.com/5654654/35482899-bdcf58dc-043b-11e8-8cc1-4c93555f4710.png) ![image](https://user-images.githubusercontent.com/5654654/35482912-cf20b3ec-043b-11e8-8902-ac871850f28c.png)

And my games seem to be detecting fine also:

![image](https://user-images.githubusercontent.com/5654654/35482923-ecf15d90-043b-11e8-8035-1fdf62eef641.png)

I see the game perfectly in Steam:

![image](https://user-images.githubusercontent.com/5654654/35482961-72785bb2-043c-11e8-8284-dfd1e17b6975.png)

But when I click Play this happens, after which I'm returned to the previous screen:

![image](https://user-images.githubusercontent.com/5654654/35482969-8680cbbc-043c-11e8-8ecd-f66b7d2a91d0.png)

**Comment by s1h4d0w** [comment]
I seem to have made 2 mistakes and was able to fix them, my bad.

The "User's glob" had to be `${title}.@(bin)` (with bin of course being the extension of your rom) and I forgot to put " around the `-L cores${/}your-emulator.dll` part (which is not in the documentation but I'm not sure if that's what fixed it).

**Comment by FrogTheFrog** [comment]
@s1h4d0w Glad that you have fixed it :) . By the way, `@(...)` is required for multiple extensions only (for example, `.@(bin|sfc)`.

@Chocobubba What is going on with these `"`? Can you test if they work for you too? Retroarch doesn't like full core path in brackets, but prefer short core path + everything in brackets?

**Comment by s1h4d0w** [comment]
Ah, I did not know which of the two fixed it, I guess it was the `"` in the path then. I was able to get both emulators to work and was able to add a third that also worked using this setup.
