### ISSUE TITLE
Suggestion: Option to Export parsers to file, or default action

### ISSUE THREAD

**Issue by NOFUNEVER** [SteamGridDB/steam-rom-manager#85]
I just got done doing a massive refresh of my whole system and meticulously backed up everything...Everything that is except srm and the 20 parers I made for it. Overlooked it hidding there in app data. It's gonna be a real pain in the but to make them over again and the whole beauty behind something like this is make them once and then your done. i'll be sure to remember next time.

**Comment by FrogTheFrog** [comment]
I'll make sure to add it in the next SRM release.

**Comment by n8jadams** [comment]
Is there any update around this? I think this is a killer feature. I see that there is this open PR: https://github.com/SteamGridDB/steam-rom-manager/pull/347

**Comment by cbartondock** [comment]
I think this is basically served by the "Open Config Directory" button I added in settings recently, since there live your "user-configurations.json" which houses all the presets.
