### ISSUE TITLE
[Bug] Local icons not working

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#86]
For cemu my config for "Local icons" is `${dir}/../${title}/meta/iconTex.tga`
When I test parser the directory is good e. g: D:/Emulation/ROMs/WiiU/SUPER MARIO 3D WORLD [ARDP01]/meta/iconTex.tga but when I do a preview the icons don't show up.

**Comment by FrogTheFrog** [comment]
@Nallat You found an incredibly stupid loophole in my logic. Technically it is not a bug and it is really hard to solve, but I will address this in next major SRM release.

What happens is:
1. Variables are replaced and resolved in `${dir}/../${title}/meta/iconTex.tga` (you get `D:/Emulation/ROMs/WiiU/SUPER MARIO 3D WORLD [ARDP01]/meta/iconTex.tga` glob).
2. Glob is passed to glob parser. Unfortunately `[ARDP01]` is now a valid glob part :/ .
3. `[ARDP01]` (as a glob) matches nothing, thus you get 0 files found.

Hopefully, this will work:
```
${dir}/../*${/\[.*?\]/g|${title}|}*/meta/iconTex.tga
```
This:
```
${/\[.*?\]/g|${title}|}
```
should remove all `[...]` parts (end result - `SUPER MARIO 3D WORLD `). Next we add globstar `*` to match anything around `SUPER MARIO 3D WORLD ` (on both sides, just in case `[...]` is at the beginning or the end). Now, we should have a valid glob:
```
`D:/Emulation/ROMs/WiiU/*SUPER MARIO 3D WORLD */meta/iconTex.tga`
```

**Comment by FrogTheFrog** [comment]
Since Chrome is not able to display `tga` files, you'll see "crossed-out eye icon". It works in Steam.

**Comment by ghost** [comment]
@FrogTheFrog Thanks ! The first solution worked

**Comment by FrogTheFrog** [comment]
I'm closing this issue it for now.
