### ISSUE TITLE
[Request] Add screenshots for a better preview of the game.

### ISSUE THREAD

**Issue by ghost** [SteamGridDB/steam-rom-manager#87]
Please add a function to download screenshot (or fanart) from IGDB or another database and place these screenshots in :
`"Steam\userdata\276642106\760\remote\GameId\screenshots"`

If it is possible to add other metadata (E. g: description of the game) please also add these metadata
E. g: 
With : 
![image](https://user-images.githubusercontent.com/36114925/36936152-715b691a-1f01-11e8-9f7b-3cc7d61acd5b.png)

Without : 
![image](https://user-images.githubusercontent.com/36114925/36936165-9758dac6-1f01-11e8-9c51-dbc08832fb05.png)

**Comment by FrogTheFrog** [comment]
IGDB is not free (https://api.igdb.com/pricing). Are there other databases like this?

**Comment by ghost** [comment]
@FrogTheFrog  Yes MobyGame : https://www.mobygames.com and Tgdb : https://thegamesdb.net

**Comment by FrogTheFrog** [comment]
Very well, I'll look into it for 3.0.0. It's a total rewrite of SRM, so keep in mind that it will take months to be released.

**Comment by ghost** [comment]
@FrogTheFrog Okay, I expect that with impatience. Thank you!

**Comment by cbartondock** [comment]
This is no longer relevant in the new Steam UI.
