### ISSUE TITLE
[Enhancement] Add support for .xpm icons

### ISSUE THREAD

**Issue by gwemmie** [SteamGridDB/steam-rom-manager#90]
I like to set a game's default icon to its emulator's, if nothing better was found. Certain emulators come with a .xpm icon, rather than png, jpg, or svg, on most Linux distributions:
-PCSX2
-DeSmuME
-Dolphin

I'm guessing ICE (which I just switched from) and now also this app don't support .xpm because Steam itself doesn't? Still, it'd be nice to not have to convert and manage those icons myself. It could probably be handled internally by steam-rom-manager, when it detected that the given icon is a .xpm file.

**Comment by FrogTheFrog** [comment]
I'm really on a fence about this. I think that user should be responsible for converting files on their own given how easy it is to do it on linux.

**Comment by gwemmie** [comment]
There's no fence to be on. This should be low priority, because it is easy to convert yourself, but on the feature wishlist, because it makes the program easier to deal with.

**Comment by FrogTheFrog** [comment]
The problem is that I would have to rely on external tool or write my own image converter. It's pain in the *** to use external tools in windows. Maybe, once 3.0.0 is released, I'll write my own converter.

**Comment by gwemmie** [comment]
Ha, good old Windows.
