### ISSUE TITLE
Ability to overwrite fuzzy finder title when game not found (Confuses old school fps Exhumed with Deus Ex Human Revolution)

### ISSUE THREAD

**Issue by NOFUNEVER** [SteamGridDB/steam-rom-manager#92]
There are a few games I've had to rename a few times to get the finder to identify the game but for the most part the Fuzzy finder has always worked wonderfully. However it seems the old school fps Exhumed(european version of Powerslave by Lobotomy Software) (for Sega Saturn/PSX ) is not in steamgriddb so it ends up matching Deus Ex Human Revolution.  It would be nice if we could save title overwrites the way we can with cover art if nothing can be found in a database.

**Comment by FrogTheFrog** [comment]
I plan to add title caching to 3.0.0. Cache will be editable.

**Comment by kencinder** [comment]
Should have commented on this awhile ago, but if you join the Discord for SRM, missing or incorrect titles on steamgriddb can be addressed.

**Comment by cbartondock** [comment]
The fuzzy cache in userdata is indeed editable. Closing
